### ISSUE TITLE
is there any way to run batch scripts in multi containers?

### ISSUE THREAD

**Issue by junneyang** [HubSpot/Singularity#1035]
run some scripts in container, and then exit.
thanks!

**Comment by ssalinas** [comment]
I'm not sure I understanding exactly what you are looking for. Are you thinking of being able to launch multiple interconnected containers at once, or something more like job dependency where one container starts the next?

Neither of those we really have support for in Singularity right now, although you could make api calls to Singularity from one job to start another. As for batches of scripts, Singularity/Mesos support downloading multiple artifacts, so you could download everything you need at once in one task and have a wrapper script you call that runs each of them.

If I'm misunderstanding the question, can you give an example use case? Hope this helps!

**Comment by ssalinas** [comment]
No response since may, closing this one
