### ISSUE TITLE
Failure while trying to run a jar file with on demand setting

### ISSUE THREAD

**Issue by the100rabh** [HubSpot/Singularity#1047]
I am trying to create a task which be run On Demand.

Below is the json for the request 
```
{
    "request": {
        "id": "ondemand1",
        "requestType": "ON_DEMAND",
        "owners": [
            "saurabh"
        ],
        "killOldNonLongRunningTasksAfterMillis": 100000
    },
    "state": "ACTIVE",
    "requestDeployState": {
        "requestId": "ondemand1",
        "activeDeploy": {
            "requestId": "ondemand1",
            "deployId": "d1",
            "timestamp": 1463652534039
        }
    },
    "type": "ON_DEMAND",
    "instances": 1,
    "hasMoreThanOneInstance": false,
    "inCooldown": false,
    "daemon": false,
    "canBeScaled": false
}
```
I deployed it using and the following is the JSON of it I got from UI
```
{
    "deployId": "d1",
    "requestId": "ondemand1",
    "deployResult": {
        "deployState": "SUCCEEDED",
        "message": "Request not deployable",
        "deployFailures": [],
        "timestamp": 1463652537563
    },
    "deployMarker": {
        "requestId": "ondemand1",
        "deployId": "d1",
        "timestamp": 1463652534039
    },
    "deploy": {
        "requestId": "ondemand1",
        "id": "d1",
        "command": "java -jar singularitytest-1.0-SNAPSHOT.jar",
        "resources": {
            "cpus": 1,
            "memoryMb": 512,
            "numPorts": 1
        },
        "uris": [
            "http://10.124.114.7/singularitytest-1.0-SNAPSHOT.jar"
        ]
    },
    "deployStatistics": {
        "requestId": "ondemand1",
        "deployId": "d1",
        "numSuccess": 0,
        "numFailures": 0,
        "numSequentialRetries": 0,
        "lastFinishAt": 1463652546070,
        "lastTaskState": "TASK_FAILED",
        "instanceSequentialFailureTimestamps": {
            "1": [
                1463652546070
            ]
        },
        "numTasks": 1,
        "averageRuntimeMillis": 442
    }
}
```

STDERR shows the following error message

> Failed to exec: No such file or directory

Just keep things simple I am printing to stdout some text in singularitytest-1.0-SNAPSHOT.jar

I tried to deploy it using run once and as a service as well, they seems work already then.
 
I could not find anything specific in the documentation regarding on demand jobs.
I am obviously missing something which I am not able to figure out. Any help is appreciated.

**Comment by ssalinas** [comment]
@the100rabh seems there is a small bug in this case. On the mesos task itself, we set the `shell` property to `false` when the arguments field is present. Meaning, args are meant to be parsed as an array and it looks for the first element to be the executable. For `ON_DEMAND` in the UI, the arguments field defaults to being set (although empty if none are specified). I will work on a fix and we can put out a bug-fix release for this. Thanks for reporting it!

**Comment by demobox** [comment]
Also ran into this - thanks for the very quick PR, @ssalinas!

**Comment by the100rabh** [comment]
Thanks @ssalinas for the quick fix

**Comment by demobox** [comment]
@the100rabh PS: Until the fix is merged, using the API to trigger an on-demand run (i.e. avoiding the UI) works for me as a workaround

```
curl -X POST <singularity-endpoint>/api/requests/request/<request-name>/run -d '{"message":"test via the API"}'
```

See:

* [`POST /api/requests/request/{requestId}/run`](https://github.com/HubSpot/Singularity/blob/master/Docs/reference/api.md#endpoint-/api/requests)
* [`SingularityRunNowRequest`](https://github.com/HubSpot/Singularity/blob/master/Docs/reference/api.md#model-SingularityRunNowRequest)

**Comment by ssalinas** [comment]
Correct, if you leave out the `arguments` field on the deploy it will work correctly. This started happening because in a UI update we started defaulting it to an empty list instead of just not setting the field

**Comment by demobox** [comment]
> Correct, if you leave out the arguments field on the run request it will work correctly.

In my case, it was the `commandLineArgs` attribute that seemed to have been doing it, but the "don't set shell if present" was the same in both cases, I think ;-)

```
{"commandLineArgs":[],"runId":"c5139a47-cd2d-4cca-a3db-8ea125323d93"}
```
