### ISSUE TITLE
Cant remove anything from interface

### ISSUE THREAD

**Issue by brat002** [HubSpot/Singularity#1062]
Error: "Could not reach the Singularity API. Please make sure SingularityUI is properly set up.
If running through locally, this might be your browser blocking cross-domain requests."

REQUEST:
`Request URL:http://10.148.60.53:7099/singularity/api/requests/request/test-service
Request Method:OPTIONS
Status Code:204 No Content
Remote Address:10.148.60.53:7099
Response Headers
view source
Allow:OPTIONS,GET,DELETE,HEAD
Date:Fri, 03 Jun 2016 13:09:14 GMT
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8,ru;q=0.6,be;q=0.4

Access-Control-Request-Headers:accept, content-type
Access-Control-Request-Method:DELETE
Connection:keep-alive
Host:10.148.60.53:7099
Origin:http://fr2-hv-60-53.iv:7099
Referer:http://fr2-hv-60-53.iv:7099/singularity/requests
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36`

**Comment by tpetr** [comment]
Thanks for the heads up, @brat002. It looks like you're having issues with CORS -- would you mind including a gist of your config YAML?

**Comment by brat002** [comment]
`# Run SingularityService on port 7099 and log to /var/log/singularity-access.log
server:
  type: simple
  applicationContextPath: /singularity
  connector:
    type: http
    port: 7099
  requestLog:
    appenders:
      - type: file
        currentLogFilename: /var/log/singularity-access.log
        archivedLogFilenamePattern: /var/log/singularity-access-%d.log.gz


mesos:
  master: zk://{{zk_line}}/mesos
  defaultCpus: 1
  defaultMemory: 128
  frameworkName: Singularity
  frameworkId: Singularity
  frameworkFailoverTimeout: 1000000
  credentialPrincipal: xxx
  credentialSecret: xxxxxxxxx

zookeeper:
  quorum: {{zk_line}}
  zkNamespace: singularity
  sessionTimeoutMillis: 60000
  connectTimeoutMillis: 5000
  retryBaseSleepTimeMilliseconds: 1000
  retryMaxTries: 3

logging:
  loggers:
    "com.hubspot.singularity" : TRACE

enableCorsFilter: true
sandboxDefaultsToTaskId: false  # enable if using SingularityExecutor

ui:
  title: Crowd Singularity
  baseUrl: http://{{ip}}:7099/singularity/
  `

**Comment by brat002** [comment]
Sorry for formatting.

**Comment by tpetr** [comment]
No worries, thanks. Is `{{ip}}` equal to `fr2-hv-60-53.iv:7099`, or `10.148.60.53:7099`? If you set it to the hostname (fr2-hv-60-53.iv:7099) I think things should start working, but regardless, `enableCorsFilter: true` should have made things work. I'll look into that.

**Comment by ssalinas** [comment]
@tpetr is correct that setting that to the hostname (`fr2-hv-60-53.iv`). `enableCorsFilter` didn't work in this case because its default methods are `GET, POST, HEAD`. We might want to update our CorsFilterBundle to add `DELETE` for our use case here
