### ISSUE TITLE
SingularityDockerInfo.parameters only supports a single value per key

### ISSUE THREAD

**Issue by chrisbrewer** [HubSpot/Singularity#1074]
`docker run` has many options that take an array for the same key.  You can see the list with `docker run --help | grep "\[\]"`.

The `parameters` field is a Map[string, string] so specifying multiple values for the same option only uses the last value for the key.  For example, to get this run command `docker run --dns 8.8.8.8 --dns 8.8.4.4 ...` you would need to add multiple dns entries with the same key like so:
```
"parameters": {
  "dns": "8.8.8.8",
  "dns": "8.8.4.4"
}
```

Since `docker run` has so many options that take an array, it would be good to have some general support for specifying them in `SingularityDockerInfo.parameters` and passing them through.

We're currently running Singularity 0.5.0, Mesos 0.26.1, and using the Mesos Docker Containerizer.

**Comment by dtabwhite** [comment]
This is actually a potential issue for us as well.  One suggestion on how make this work in a generic way is to basically ignore the key when generating the docker command line args and only take the value.  So the example above would be:

```
"parameters": {
  "--dns": "--dns 8.8.8.8 --dns 8.8.4.4"
}
```

The downside of this is that even though `parameters` is still a Map, it's not backwards compatible wrt how people are using that map now.  For that reason, perhaps a better approach would be simply to have a new `parametersList` that is an array of arbitrary parameters to pass to docker.
