### ISSUE TITLE
Cannot remove request that contains the character %

### ISSUE THREAD

**Issue by MaximeDevalland** [HubSpot/Singularity#1094]
Hello,

I mistakenly created a request with the character " % " in the name.

Here is what I get when trying to delete it :
```
DELETE http://singularity.local/api/requests/request/myrequest%build.number% 400 (Bad Request)
```

I was able to reproduce the error with the latest version of Singularity on my local.

**Comment by tpetr** [comment]
Sorry for the headache there -- the best way to fix this is probably to delete the node in ZooKeeper. Feel free to ping us on Slack if you need help here.

https://github.com/HubSpot/Singularity/pull/1031 added improved ID validation, and we'll be cutting a new release with this change soon.

**Comment by MaximeDevalland** [comment]
Thanks Tom for this fast reply.

**Comment by ssalinas** [comment]
#1031 is now out in the 0.8.0 release, going to close this
