### ISSUE TITLE
First argument is dropped when invoking a command with args?

### ISSUE THREAD

**Issue by demobox** [HubSpot/Singularity#1114]
Given the following deploy

```
{
  "deploy": {
    "requestId": "test",
    "id": "1",
    "command": "/bin/sh",
    "arguments": [ "dummy-arg", "./some-script.file.sh" ],
    "uris": [
        "s3a://path/to/some-script.file.sh"
    ]
      }
}
```

`./some-script.file.sh` is successfully executed. I.e. the task doesn't fail even though `dummy-arg` is invalid, and the analogous shell invocation from the command line fails:

```
/tmp/mesos/slaves/.../786d0186-9038-4109-8678-03eb65771267# /bin/sh dummy-arg ./some-script.file.sh
/bin/sh: 0: Can't open dummy-arg
```

From Singularity, the command succeeds:

![screen shot 2016-06-27 at 19 37 23](https://cloud.githubusercontent.com/assets/223702/16399324/6423d020-3c9f-11e6-993d-5178896e75a3.png)

![screen shot 2016-06-27 at 19 45 47](https://cloud.githubusercontent.com/assets/223702/16399378/cd1b1d4a-3c9f-11e6-90c2-74553e491b02.png)

It appears the Mesos task is being constructed as one would expect:

```
        "mesosTask": {
            ...
            "command": {
                ...
                "value": "/bin/sh",
                "shell": false,
                "arguments": [
                    "dummy-arg",
                    "./some-script.file.sh"
                ]
            }
```

So this may well be an underlying issue with the Mesos executor, related to e.g. https://issues.apache.org/jira/browse/MESOS-2859?

**Comment by ssalinas** [comment]
Unless you are using something besides the mesos executor, then yeah I'd say that's mesos' issue. You're correct the mesos executor can be confusing.

If you need to fool with the shell setting to get things working the way you want, we did add support to override the shell true/false in #1049, by setting `shell` on the `SingularityDeploy`

**Comment by demobox** [comment]
Thanks for taking a look, @ssalinas! For general reference, here a quote from the [`execlp` documentation](http://linux.die.net/man/3/execlp), which is the command the Mesos executor is executing:

"The first argument, by convention, should point to the filename associated with the file being executed."

So in the case of the example above, the "correct" specification would have been, I guess:

```
"command": {
                ...
                "value": "/bin/sh",
                "shell": false,
                "arguments": [
                    "/bin/sh",
                    "./some-script.file.sh"
                ]
```
