### ISSUE TITLE
Allow support for list of parameters in SingularityDockerInfo

### ISSUE THREAD

**Issue by subratbasnet** [HubSpot/Singularity#1168]
Docker parameters support parameters with the same name, such as:

`--log-opt max-size=5m
--log-opt max-file=2`

I tried passing parameters as {"log-opt max-size":"5m", "log-opt max-file":"2"}, but it did not work.

How can we handle such cases?

Thanks

**Comment by tpetr** [comment]
Hey @subratbasnet -- this is a known issue that we're tracking in #1074. Closing this issue to minimize dupes.
