### ISSUE TITLE
expose particular docker-related ID

### ISSUE THREAD

**Issue by pennello** [HubSpot/Singularity#1204]
I see a final column `NAMES` in the `docker ps` output.

```
CONTAINER ID        IMAGE        COMMAND                   CREATED             STATUS              PORTS                                          NAMES
0848de3cf1b9        ...          "/srv/bootstrap/launc"    18 minutes ago      Up 18 minutes       0.0.0.0:31223-31224->31223-31224/tcp           mesos-d3849450-1ee9-44c9-9aa4-2314330da01b-S1.244e66a9-a799-4e01-9ae2-d24e4d21197e
2dbcb3eb7128        ...          "/bin/sh -cx 'eval \"e"   3 hours ago         Up 3 hours          0.0.0.0:31399->31399/tcp                       mesos-d3849450-1ee9-44c9-9aa4-2314330da01b-S1.126faa09-d49c-4e52-910e-efb3e9decb6a
c0aaae7aa0b7        ...          "node server/src/star"    3 hours ago         Up 3 hours                                                         mesos-d3849450-1ee9-44c9-9aa4-2314330da01b-S1.e46ddaf7-ded2-4330-841d-4ef6d3e6566e
```

It has values like `mesos-d3849450-1ee9-44c9-9aa4-2314330da01b-S1.e46ddaf7-ded2-4330-841d-4ef6d3e6566e`, which look like `mesos-<slave ID>.<some other ID>`.

Is it possible to get that "some other ID" in an API request to Singularity?

On the task API response, `task/<task ID>`, I see it show up at the end of the directory value.

```
"directory": "/mnt/mesos-slave/slaves/d3849450-1ee9-44c9-9aa4-2314330da01b-S1/frameworks/Singularity/executors/<task ID>/runs/ffa29fb6-3788-4ad1-a9e2-80852d59a238",
```

But this key, not too surprisingly, doesn't show up under, for example, a call to `tasks/active`.  Perhaps it could be included under the Docker container info?

```
"containerInfo": {
    "type": "DOCKER",
    "docker": {
        "image": "...",
        "privileged": false,
        "network": "HOST",
        "portMappings": [],
        "forcePullImage": false,
        "parameters": {}
    }
},
```

What I'm looking for is a (virtually) race-free way to connect task information that I get from the API with being able to uniquely identify a running container on an actual slave host.

cc @stevenschlansker

**Comment by ssalinas** [comment]
So, at the moment mesos does not expose that value (the mesos slave container id). There is an open issue for them to start returning it on task status messages, but doesn't look like much forward progress has been made yet: https://issues.apache.org/jira/browse/MESOS-2191

In our own custom executor we were getting it parsing the sandbox directory for a while, that was the only place I could find that it was returned

**Comment by ssalinas** [comment]
apologies, linked to wrong mesos issue. Will continue looking for what happened with that

**Comment by pennello** [comment]
@ssalinas 
> In our own custom executor we were getting it parsing the sandbox directory for a while, that was the only place I could find that it was returned

Yeah, this was my plan too, but `directory` doesn't come through in `tasks/active`.  Maybe the stop-gap is to expose it there too per-task?

**Comment by pennello** [comment]
@ssalinas Any thoughts on just exposing `directory` in at least `tasks/active`?

**Comment by ssalinas** [comment]
directory is already exposed in the `task/<task ID>` api response, are you looking for it somewhere else as well?

**Comment by pennello** [comment]
@ssalinas 
Right!  Specifically, `tasks/active`.  The use case is to do _one_ call to the Singularity API, filter by task ID or request ID and then have a race-free identifier to be able to use to go in and do Docker-ish things.

If I want that information for many tasks, having to do hundreds of `task/<task ID>` calls would be overhead-prohibitive.  : /

I could imagine an argument for including it in `tasks/scheduled` (if it's defined), `tasks/lbcleanup`, `tasks/cleaning`, etc.

**Comment by pennello** [comment]
> Ah, didn't realize we weren't exposing the whole task info there. Yeah we can probably add a piece in the `SingularityTask` object on that endpoint

Nice.

**Comment by pennello** [comment]
I presume this did not make it into 0.10.0?

**Comment by ssalinas** [comment]
@pennello no it didn't. It's not as trivial of a change as I originally thought. Will work on this for an upcoming release though

**Comment by pennello** [comment]
@ssalinas Right on.

**Comment by pennello** [comment]
Ping, @ssalinas.  : ]
