### ISSUE TITLE
Singularity UI 404's on direct access

### ISSUE THREAD

**Issue by jaredstehler** [HubSpot/Singularity#1237]
With version `0.10.0`, every time I directly access a UI url it shows a 404 screen. This wasn't happening with versions 0.7-0.9. When I click any link in the UI it works fine, but using the back button also results in 404's. 

Example: Refreshing a page or accessing `myserver.com/singularity/`:

<img width="1005" alt="screen shot 2016-08-21 at 12 50 00 pm" src="https://cloud.githubusercontent.com/assets/2022218/17838544/cdbede84-679d-11e6-98ee-929a6bbb5d05.png">

Then clicking on the `go home` link takes me to a working page with the same url.

Not sure if this has anything to do with my proxy settings:

`singularity.yaml`:

```
server:
  type: simple
  applicationContextPath: /singularity
  connector:
    type: http
    port: 7092
```

`/etc/nginx/conf.d/proxy/singularity.conf`:

```
location  /singularity {
    proxy_pass_header Server;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme $scheme;
    proxy_set_header X-Request-Start "${msec}";
    
    proxy_pass http://singularity;
    
    proxy_connect_timeout 55;
    proxy_read_timeout 60;    
}
```

`/etc/nginx/conf.d/upstreams/singularity.conf`:

```
upstream singularity {
    server myserver.com:7092;
}
```

**Comment by ssalinas** [comment]
@jaredstehler what do you have for the `ui` settings portion of your config? Specifically the `baseUrl` field?

**Comment by Calvinp** [comment]
Opened #1238 to (hopefully) fix this.

**Comment by intellify-chef** [comment]
thanks!
