### ISSUE TITLE
Polyfill ES6 Symbol?

### ISSUE THREAD

**Issue by stevenschlansker** [HubSpot/Singularity#1269]
My browser still isn't fully on the ES6 train:
```
[09:41:01.313] ReferenceError: Symbol is not defined @ http://singularity-qa-sf.otenv.com/static/js/app.js:247
```
I'm probably not the only one -- I know it's a pain to not be able to use the latest and greatest, but hopefully just dropping in a polyfill fixes the problem?

**Comment by ssalinas** [comment]
Fixed in 0.11.0 release
