### ISSUE TITLE
Singularity should support healthchecks on statically defined service ports

### ISSUE THREAD

**Issue by dtabwhite** [HubSpot/Singularity#1287]
For some services we need to define the ports statically.  While we can do this with network=BRIDGE mode services with static portMappings, this is not possible with network=HOST mode services since the current healthchecks are based on ports defined in portMappings.  So for network=HOST services it would be nice to be able to specify one or more healthchecks that can include a statically defined port.

**Comment by ssalinas** [comment]
This will be available once #1306 is merged. Should make it into 0.14.0 release. On the Singularity deploy there is now a `healthcheck` field which corresponds to the [`HealthcheckOptions`](https://github.com/HubSpot/Singularity/blob/hs_stable/SingularityBase/src/main/java/com/hubspot/deploy/HealthcheckOptions.java) class. A `portNumber` field is available in `healthcheck` to define a particular port to use for the health check.
