### ISSUE TITLE
Allow running more than 1 "Run now" (on demand) tasks per request at once

### ISSUE THREAD

**Issue by bbeaudreault** [HubSpot/Singularity#129]
Steps to reproduce:

Go to a request.  Click Run Now.
Task starts.
Go back to request.  Try Run Now again.
Dialogue goes away as if it succeeded, but nothing ever happens.

Ideally this would launch a second (or 3rd, 4th, etc) task.  At the very least it should throw an error letting us know only 1 is allowed.

**Comment by wsorenson** [comment]
Fixed in https://github.com/HubSpot/Singularity/commit/dba1857e3b5f6b8d6ed5ca050a4d56b2c955f787
