### ISSUE TITLE
Missing link to stdout/stderr on task page

### ISSUE THREAD

**Issue by kchaliki** [HubSpot/Singularity#1296]
Hello everyone, 

We have occasionally noticed that under some task pages, under the Files bit, there is a message that "No files exist in task directory." and there is obviously no link to stdour/stderr. We also noticed that in those cases there is no "Directory" box between "Task ID" and "Hostname" and the "directory" bit is missing from the tasks' JSON representation.

We can however find the folder and stdout/stderr from the normal Mesos page and comparing to other tasks where everything is in order I can't see anything obvious standing out, the paths look similar apart from the obvious naming/timestamp etc differences.

Any ideas what could be going and anything else I can do to help debug? I imagine somehow the folder information never makes it back to the Singularity scheduler somehow?

**Comment by ssalinas** [comment]
Hey @kchaliki a few things to help debug:
- What version of Singularity and what version of mesos are you running?
- When you see this issue are there any errors in the console?
- Are the tasks generally in a state like `STARTING` or `LAUNCHING` when you see this, or do you also see it for `RUNNING` or other states of tasks?

**Comment by kchaliki** [comment]
Hello @ssalinas, 

- Running mesos_version: "0.25.0", singularity_version: "0.8.0"
- By console, do you mean the mesos master log, singularity log or something else?
- We see it through the entire lifecyle, the example I am looking at started and ran for ~40 mins and produced output but the directory never seemed to have come through

History
Status	Message	Time
Task killed	Command terminated with signal Terminated	4 hours ago (21 Sep 2016 10:30)
Task running	—	5 hours ago (21 Sep 2016 09:51)
Task launched	Task launched because of UNPAUSED ()	5 hours ago (21 Sep 2016 09:51)

**Comment by ssalinas** [comment]
Was thinking of the browser console (js errors). Wondering if one of the api calls to Singularity to fetch directory/files data failed, which would show up there.

**Comment by kchaliki** [comment]
Yes I do see some errors in the Javascript console in fact but I am not sure that is the problem... If the directory is completely missing from the output that pops up when pressing the JSON button, isn't that a sign of something more fundamental going wrong?

**Comment by kchaliki** [comment]
Right - here is an interesting log message!

Task betdaqdist_tennis_coordinator-betdaqdist_tennis_coordinator_deploy0-1474474554335-1-db02.stratagem.co-DEFAULT does not have a directory yet - check again soon (enqueued request to refetch)

**Comment by kchaliki** [comment]
@ssalinas so do you think there is an actual bug here or perhaps something transiently going wrong which the browser never recovers from?

**Comment by ssalinas** [comment]
Seems Singularity is having trouble fetching the directory from the mesos slave. Would it be possible to gist log lines related to a task or to the MesosClient where this is happening (i.e. grep for the task id and/or `MesosClient`)? Would be helpful to see if there are any related exceptions in the logs when it is trying to hit the mesos slave api

**Comment by kchaliki** [comment]
I did some grepping on both the singularity and mesos slave logs for another example I found - results below. My untrained eye doesn't see any error messages. However I think I see a pattern here, the ones that don't work I *think* all happen to have been scheduled be on the same host the mesos master and the singularity scheduler have are running on, could that be the source of the problem?

https://gist.github.com/kchaliki/199dc7b8c76ee0669f99a2efaf51f9c5

**Comment by ssalinas** [comment]
Ah sry, was unclear there. I was talking about the Singularity log (stdout for Singularity, not access logs). That should have much more information

**Comment by kchaliki** [comment]
Sorry still learning here! :)

So the singularity log in upstart is full of these, around the time the job started, died and I think every time I opened the page on the UI.

ERROR [2016-09-22 12:21:18,903] com.hubspot.singularity.mesos.SingularityLogSupport: While fetching directory for task: betdaqdist_tennis_coordinator-betdaqdist_tennis_coordinator_deploy0-1474546878586-1-db02.stratagem.co-DEFAULT

Full grep of the log here

https://gist.github.com/kchaliki/3d380f5988e813e97f0125c34942fac5

Does the fact this seems to happen when the task is scheduled on the same box as the master spark any suspicions?

**Comment by ssalinas** [comment]
Hmm it might be, looks like Singularity can't hit `http://(slave hostname):5051/slave(1)/state` according to that log. Next things I would do:
- check if you mesos slave is listening on a port other than 5051
- check that the machine where Singularity is running can connect to that slave on that port (i.e. check for any network security that may be interfering)

**Comment by kchaliki** [comment]
- Yes seems to be
- I can wget the state page just fine from the host itself (remember singularity and the mesos slave are running on the same host for the problematic cases) using that URL, I can find the job in question in the state page and it's "directory" field in the JSON description... How strange! If you happen to have the piece of Java code that runs the wget equivalent in Singularity I can give it a go in case it's some Security Manager issue or something?

**Comment by kchaliki** [comment]
In fact I can get the code myself so bear with me

**Comment by kchaliki** [comment]
@ssalinas sorry been a bit busy but just tried this out and I think I can reproduce. I wrote the following code by extracting bits from the Singularity codebase

https://gist.github.com/kchaliki/4214b95a4c7ed3d12917a83420e46e25

and running from a separate host to the mesos slave it works fine but running from the host itself I get a pretty angry exception pasted here. Note how the address has been changed to 127.0.01. Do you see the problem perhaps?

https://gist.github.com/kchaliki/5a388d83b241663c3ca67fe448c90983

**Comment by ssalinas** [comment]
@kchaliki since you are getting a connection refused, wondering if it has to do with the `--ip` flag (http://mesos.apache.org/documentation/latest/configuration/). Guessing that the mesos slave is listening on the resolved IP but not on `127.0.0.1`. Can confirm that by seeing if you can run that same thing on a different host and have it succeed (since it will then not resolve to `127.0.0.1`). If that is the case, you'll either want to move that mesos slave off of the same machine as Singularity, or make sure that the `db02.stratagem.co` address resolves to the internal/external ip rather than resolving to `127.0.0.1` to fix the issue

**Comment by kchaliki** [comment]
I see, ok will figure out, thanks for the help!
