### ISSUE TITLE
History of "Run Now" extra command line arguments

### ISSUE THREAD

**Issue by bbeaudreault** [HubSpot/Singularity#130]
For the ```Additional command line input (optional):``` box, it would be great if there was a history of what option combinations had been used in the past.  I often find myself running the same commands or similar commands, but adding another procfile definition would be overkill.

This is similar to the use case of being able to ```ctrl-r``` to step through bash history, when we ran these commands on the servers.

**Comment by tpetr** [comment]
implemented in https://github.com/HubSpot/Singularity/pull/708
