### ISSUE TITLE
Add a timeout for decommissioning

### ISSUE THREAD

**Issue by eherot** [HubSpot/Singularity#1322]
We like to be able to decommission nodes automatically (for automatic reboots) but in the event that a decommission can't succeed (missing artifacts, etc), having a cluster that can't start new tasks because of a node that's been sitting helplessly in this state for hours is not helpful.

**Comment by ssalinas** [comment]
@eherot started the process of hooking up machine states to our existing expiring object code here: https://github.com/HubSpot/Singularity/pull/1342

**Comment by ssalinas** [comment]
Released in 0.13
