### ISSUE TITLE
Can't deploy services to all hosts when using fixed ports

### ISSUE THREAD

**Issue by relistan** [HubSpot/Singularity#1323]
I may just be doing something wrong here so if that's the case, advice is appreciated. But what I'm seeing is that I am not able to deploy services with fixed ports if an existing service is already running. Here's the scenario:

* Service in a Docker container
* Running in HOST networking mode
* Binding to a fixed port on each host where it runs (this is hard requirement)

I want to deploy with the rolling deployment where it handles one instance at a time. But it doesn't seem like I can tell the deployment to bring an existing instance down before trying to start the new instance. When you are using a service with a fixed port, this means the deployment is a non-starter. I currently have these settings:

```json
        "deployInstanceCountPerStep": 1,
        "deployStepWaitTimeMs": 10000,
        "autoAdvanceDeploySteps": true
```

Even without those settings, though, with the non-rolling deploy it of course has the same problem. Is there a setting I'm missing? I've been all over the docs and code and don't see one. Here's the status for the failed deployment:

 > Only 0 of 2 tasks could be launched for deploy, there may not be enough resources to launch the remaining tasks

**Comment by ssalinas** [comment]
@relistan How many slaves are you running vs # of instances in that deploy, and are there any other constraints (attributes/etc) on the placement? My first thought is that you are either generally low on resources, or some other constraint is limiting where the tasks can run in such a way that you can't find enough free space to launch one.

 If you look in the Singularity logs, for each offer that comes in there should be a `TRACE` level line like `Rejecting SEPARATE task {request id} from slave {slave} ...` or any other `TRACE` level log line from the `SingularitySlaveAndRackManager` class that might give some more insight.

**Comment by relistan** [comment]
Thanks @ssalinas . There were two things going on and the resource message was a red herring. However the main issue still remains so I'll try to re-explain the scenario:

 * The service needs to run on all of the slaves or as nearly as possible
 * Needs to bind on a fixed port

The problem is that in this scenario I need to be able to take down an instance _before_ starting a new one. If I don't, the port will not be free on potentially any hosts, and therefore no new instances will be able to start in the new deploy. 

Currently the staged deployment starts a new task and then either waits for it to be healthy or waits for it to be up depending on your health check settings, then takes down one task from the previous deployment. The problem is that no tasks from the new deployment ever start properly. I have been able to hack around this by putting a process manager in the container that continually restarts the process inside the container and turning off health checks. Singularity sees the task as "up" even though it's continually restarting until Singularity kills off the previous task. I really don't want to run it that way.

But, if there is a setting that allows me to just take down a task from the previous deploy _before_ starting a task in the new deploy, that would be ideal.

I took a look through the code with the intent of implementing this but thought I'd ask about it first in case it's a misunderstanding.

**Comment by ssalinas** [comment]
Ah, yes I misunderstood the original ask. Two responses:
- Currently we don't have a setting for deploying a task to all slaves, although it's something we've been trying to think how to do for a while (see #469)
- There isn't an option right now for taking down tasks _before_ starting up new ones. Our deploys always go in favor of being over capacity rather than under.

**Comment by relistan** [comment]
Thanks @ssalinas . I had assumed that #469 was about not being able to guarantee that it would run on every single machine, not about the ability to deploy a service on all machines in the best case. There was discussion about this on the Marathon GitHub Issues: https://github.com/mesosphere/marathon/issues/846 and whether or not Mesos could even support that . Singularity has the major advantage of not needing to share the Mesos cluster with another framework, however, so resource issues aside, it seems feasible.

Agreed, normally you want to over-provision on deployment. But in the case where a particular port is required for a service you can't do that. For reference, I want to combine Singularity with my work on [Sidecar](https://github.com/newrelic/sidecar) which needs to run on each machine and would stand in for Baragon (we already run Sidecar everywhere). Ideally Sidecar will get deployed via the same scheduler as everything else. Worst case we'll have to do it out of band. I'll spend some time in the Singularity code and see if I can figure out what would be required to do that. Closing for now. Will re-open with a PR if I make any progress.

Thanks for your help!
