### ISSUE TITLE
Allow requiredSlaveAttributes for requests to be set via the UI?

### ISSUE THREAD

**Issue by demobox** [HubSpot/Singularity#1327]
Picking up, to some extent, the discussion from #218: Singularity already supports [`requiredSlaveAttributes` for requests](https://github.com/HubSpot/Singularity/blob/master/Docs/reference/api.md#-singularityrequest), and they work as intended (thanks for adding them!).

However, they - and quite a few of the other possible attributes, but that's perhaps a different discussion - cannot be set via the UI. In our environment, whilst deploys are practically always created programmatically, requests are still quite often created manually as a one-off step, and these requests thus end up without the desired placement constraints, and then need to be detected and patched later.

Does making more of the request attributes configurable via the UI seem like a legitimate part of the roadmap? Or would the advice be to simply "stop doing that", and to ensure all requests are created programmatically?

**Comment by ssalinas** [comment]
@demobox , what version of Singularity are you running. In the release of `0.10` we went through and confirmed all fields were accessible in the request edit/create form as part of our revamp of the ui (which I just confirmed does have `requiredSlaveAttributes`). If there are specific fields you find missing in releases after 0.10 please let us know and we will add them

**Comment by demobox** [comment]
> what version of Singularity are you running.

Err...caught me out there ;-) We're actually _just_ migrating over to 0.11.0 this morning, and I haven't looked at the UI screen yet. The migration is on hold while we look into some "Empty response from server" issues that we didn't see on the old version, but there are more changes than just the Singularity version in play, and that's a different discussion in any case...

Thanks for clarifying!

**Comment by demobox** [comment]
Nice ;-)

![image](https://cloud.githubusercontent.com/assets/223702/19810448/7da8a144-9cfb-11e6-99ac-58aa08f8fb13.png)

Thanks, Singularity devs!
