### ISSUE TITLE
Add endpoint to update owners of a request

### ISSUE THREAD

**Issue by nyarly** [HubSpot/Singularity#1329]
At the moment it appears to require the deletion of a Request to change its owners. Since a running Request might change ownership over time, without needing a redeploy, it seems untoward to require downtime for such a change.

What I'd like to propose (in advance of submitting a PR for) is the addition of 
`PUT /api/requests/request/{requestId}/owners` to replace the existing owner list for a Request.

**Comment by ssalinas** [comment]
@nyarly You can `POST` new request data to the `/api/requests` endpoint (e.g. same data except for updated owners). This does not initiate a redeploy and will update the request data. You can also go to the `/requests/edit/{requestId}` path in the ui (or get there via the `edit` link on the request page) and change the owners of the request there.

**Comment by nyarly** [comment]
Okay, thanks.

**Comment by nyarly** [comment]
Quick aside, then: why are there `scale` and `skipHealthchecks` endpoints then?

**Comment by ssalinas** [comment]
Those were meant as convenience endpoints for easier use by the UI (i.e. not needing the whole request json), but also ended up taking on some other functionality when we added expiring actions for skipping heathchecks and scaling
