### ISSUE TITLE
The method runSingularityRequest() on SingularityClient should return the JSON response

### ISSUE THREAD

**Issue by billwright** [HubSpot/Singularity#1337]
Currently this method returns void. How is the user to determine the success or failure of the run? At the very least this method should return the runId. That way the user could then query for the history of that run (via the /api/history/run/<runId>) and from that get the taskId and then query the history of the task to finally get the results and return code of the run. 

Ideally, the method would return a SingularityRun object which would have methods to query the status and, once finished, to get the SingularityTask or possibly just have the return code results (currently embedded in the statusMessage of the Task JSON).

**Comment by tpetr** [comment]
That's a good point, thanks. #1338 should accomplish what you need (PRs are always welcome 😄). You'll be able to grab the task's runId via `SingularityPendingRequestParent.getPendingRequest().getRunId()`.

Thanks for using Singularity!

**Comment by billwright** [comment]
Well, that is most excellent! Any idea when that will be available? I'd be happy to contribute to this project with a PR but I was daunted by the testing aspects of this. Here's the code I'd like to have in my client (feedback to modify it welcomed):

` List<String> commandLineArgs;
   Optional<SingularityRequestParent> singularityRequest = singularityClient.getSingularityRequest("generic-launcher-svc-test-app-1");

   SingularityRunNowRequest singularityRunNowRequest = new SingularityRunNowRequest(null, null, null, commandLineArgs);
   SingularityPendingRequestParent pendingRequest =          singularityClient.runSingularityRequest(myRequestId, singularityRunNowRequest);
   
  String runId = pendingRequest.getPendingRequest().getRunId();

// Pseudo code:
 SingularityRun run = singularityClient.getRun(myRequestId, runId)
// For the above I'd use GET /api/history/request/{requestId}/run/{runId}

SingularityTask task
do {
     task = singularityClient.getTask(run.taskId)
    // for the above I'd use GET /api/history/task/{taskId}
} while (task.taskUpdates.last().isFinish())

Integer returnCode = 0;
if (task.hasFailed()) {
     returnCode = parseStatusMessageForReturnCode(task.statusMessage)
}
// The statusMessage in my failure case looks like this:
//  "Docker container run error: Container exited on error: exited with status 11"

`

**Comment by ssalinas** [comment]
Released in 0.12.0 :)

**Comment by billwright** [comment]
Sweet! Thanks. Any thoughts on my pseudo code above? Pointers to the best way to do something like this with the existing API. I know I should put in a PR for this and I might end of doing that, but I've pretty much implemented the above in my code for now.

**Comment by ssalinas** [comment]
@billwright you should be able to do something fairly similar to what you have, you'll just need to poll for the task id since it will take a few moments between requesting the run and the task starting. The `getHistoryForTask({request id}, {run id})` is what you want. If the task hasn't started yet, it will return an `Optional.absent` and will return the object once the task has started (giving you the task id)

**Comment by billwright** [comment]
Yes, this is exactly what I'm doing now. I might try to roll this into the API and submit a PR as I want to use it across multiple projects. Thanks.
