### ISSUE TITLE
Minor healthcheck UI improvements

### ISSUE THREAD

**Issue by stevenschlansker** [HubSpot/Singularity#1356]
Currently healthchecks sort oldest to newest, the reverse might be more useful?

If a task is bouncing, and the new tasks are launched but not yet healthy, the status will show as `TASK_RUNNING` for the new (unhealthy) instances and `TASK_CLEANING` for the old (but healthy) instances.  This is a little confusing to the end user, they think that since one is "cleaning" it is being killed and since one is "running" they say "why hasn't my deploy succeeded yet???"

The behavior is fine, it's just the messaging that could use improvement -- maybe a little badge next to healthy vs unhealthy instances?  Or a `TASK_RUNNING_NOT_YET_HEALTHY` state?

**Comment by ssalinas** [comment]
#1626 is a step towards this. It exposes tasks which are healthy/not yet healthy and we can use that to inform the ui in future PRs

**Comment by ssalinas** [comment]
There is a healthy/not yet healthy indicator next to tasks in the ui in the most recent release. Closing this one
