### ISSUE TITLE
Log tailer is very slow / induces browser lag

### ISSUE THREAD

**Issue by stevenschlansker** [HubSpot/Singularity#1358]
I've noticed that the Singularity log tailer is often not very responsive, and simply having it open (even in a background tab) can negatively affect browser performance.  Closing the window offers immediate relief.  I wonder if there is something obvious, maybe a memory leak, that causes poor performance.  It seems to get worse the longer you have the log file open.

**Comment by ssalinas** [comment]
tailer improvements are already coming in https://github.com/HubSpot/Singularity/pull/1253

**Comment by ssalinas** [comment]
New log tailer code has been merged and will be in next release 👍
