### ISSUE TITLE
Singularity web service bind ip

### ISSUE THREAD

**Issue by petrovicboban** [HubSpot/Singularity#1378]
Hi,  
is it possible to bind singularity service to 127.0.0.1?

**Comment by ssalinas** [comment]
Yes, the Singularity web service is built on dropwizard. The `SingularityConfiguration` yaml extends the dropwizard configuration settings. You can see the section around ports and bindings at http://www.dropwizard.io/0.7.1/docs/manual/configuration.html#man-configuration-connectors
