### ISSUE TITLE
Hostname constraints

### ISSUE THREAD

**Issue by petrovicboban** [HubSpot/Singularity#1390]
Hi,  
is it possible to set execution of some requests only to specific hostnames? Or I have to set custom attributes to them and use 'required slave attributes' feature?  
Second solution would require mesos slave restart, and cleaning mesos data folder, so all running tasks would be lost. Thats why I would prefer the first one, if possible.

**Comment by pgillet** [comment]
Hi,

How does it work and what are exactly those attributes? Do they refer on environment variables on slaves?
What is the attribute's key in this case, "hostname" ?

Thanks

**Comment by petrovicboban** [comment]
Hi,  
thats related to mesos itself [attributes and resources]( http://mesos.apache.org/documentation/latest/attributes-resources/ ) not Singularity particular.  

Atrribute's key can be any string that has some meaning to you, including 'hostname'
