### ISSUE TITLE
no control over mesos server port and respective domain:port value advertised to mesos 

### ISSUE THREAD

**Issue by captify-akraievoy** [HubSpot/Singularity#1413]
We've attempted running singularity from within kubernetes next to a separately hosted mesos cluster. Singularity UI is reachable and works fine, but mesos tries to connect to singularity using internal kubernetes domain name (or seemingly random kubenet IP) and seemingly random port. 
In case we could control the below:
* the port number, which is locally bound, and
* the advertised domainname:port which mesos observes
we could integrate the services. 

We would still have to manually forward traffic from hand-crafted DNS name and port-number to kubernetes kubenet IP and port, but integration at least becomes possible this way. 

For now, there's no way to configure that at all.

**Comment by tpetr** [comment]
You should be able to accomplish this by setting one or more of the `LIBPROCESS_*` environment variables (http://mesos.apache.org/documentation/latest/configuration/, search for "Libprocess Options").

**Comment by ssalinas** [comment]
Closing since this is a mesos setting, not a singularity issue
