### ISSUE TITLE
Artifacts cache

### ISSUE THREAD

**Issue by bydga** [HubSpot/Singularity#1416]
It seems, that currently the artifacts (specified in `uris` field of a SingularityDeploy) cannot be marked as cacheable by the Mesos fetcher: described in http://mesos.apache.org/documentation/latest/fetcher  (chapter Fetching through the cache)

Are there any plans of implementing this? Or I am able to help with this feature (as we are interested in this functionality) - what would be the best way of doing it? Encapsulating the `uris Array[string]` into an object `uris Array[ArtifactItem]` with fields `uri, executable, extract, cache` ?

**Comment by ssalinas** [comment]
Internally we use the Singularity custom downloader, so we hadn't implemented the cache field for the basic uris. We can definitely make those into an object.

**Comment by ssalinas** [comment]
Fixed in https://github.com/HubSpot/Singularity/pull/1417
