### ISSUE TITLE
Deploy UI ignores Docker parameters entered

### ISSUE THREAD

**Issue by billwright** [HubSpot/Singularity#1420]
I'm running Singularity 0.9.0. When I set the Docker parameters in a deploy, like that shown in this screenshot:

![screen shot 2017-02-09 at 1 28 53 pm](https://cloud.githubusercontent.com/assets/669916/22801858/c26a62b4-eecb-11e6-9038-a3619d228820.png)

 they don't show up in the JSON of the deploy, when I view the deploy JSON via the UI, which looks like this:

```json
"deploy": {
        "requestId": "generic-launcher-svc-test-app-1",
        "id": "0209.7",
        "command": "",
        "containerInfo": {
            "type": "DOCKER",
            "docker": {
                "image": "pdocker.valkyrie.net/odc/generic-launcher-svc-test-app:1.1.2",
                "privileged": false,
                "network": "HOST",
                "portMappings": [],
                "forcePullImage": false,
                "parameters": {}
            }
        },
```

I expect the parameters section to include the parameters I entered. The hope is that this will turn into a docker run command like this:

```
docker run --user 616573731 <image-hash>
```
I get no error in creating the deployment and they are not used when starting up the Docker container. I was hoping they were used like parameters are used in a Docker container deploy via Marathon.

The API for this functionality is a bit confusing as well. It has dockerParameters and parameters. For Marathon the parameters need to be formatted as a list of JSON objects like this:

```
{ "key": "user", "value:, "616573731" }
```

Perhaps I need to enter the '--' with my parameter name? Perhaps I need to add them as key=user and value=616573731, but that wouldn't make much sense to require that in the UI...

Not sure if this is related to my problem, but whenever I visit the page for this deploy I get this error popping up:

![screen shot 2017-02-09 at 1 38 31 pm](https://cloud.githubusercontent.com/assets/669916/22802332/a17c7860-eecd-11e6-91de-f1c0168e1b16.png)

**Comment by ssalinas** [comment]
Hey @billwright , we changed over to the style you mentioned back in https://github.com/HubSpot/Singularity/pull/1169 . `dockerParameters` is the new style of field (with key/value as individual fields), `parameters` is the old (and deprecated one)

I can check, but I'm guessing the ui did not get updated with the PR, so we can fix that. As for the deploy page, probably a separate issue, but we can fix that as well

**Comment by billwright** [comment]
Thanks @ssalinas for the response. So, that probably means that the 0.11.0 version doesn't have the UI fix either. If the API works, though, that should be fine for now. I notice that when I pull down the repo it is version 0.13.0. Is 0.12.0 in the release process?

I'd love to help out on some of this, but I can't get singularity to come up via docker-compose. I put in an issue/question on that as well. If you can help me out there, maybe I can contribute something to this project. 

Bill

**Comment by ssalinas** [comment]
Fixed in https://github.com/HubSpot/Singularity/pull/1423

**Comment by billwright** [comment]
Just to be clear @ssalinas , I cannot set docker parameters even via the API with version 0.9.0, right? I need this to set the user for the docker container. I submit JSON like this:

```json
{
   "deploy":{
      "id":"MyTestDeploy.939460",
      "requestId":"MyTestRequest-938634",
      "command":"",
      "env":{
         "SVC_ENVIRONMENT":"ci",
         "VERSION":"1.0.0-1"
      },
      "containerInfo":{
         "type":"DOCKER",
         "docker":{
            "network":"HOST",
            "image":"pdocker.valkyrie.net/odc/generic-launcher-svc-test-app:latest",
            "dockerParameters":[
               {
                  "value":"616573731",
                  "key":"user"
               },
               {
                  "value":"my-singularity-app",
                  "key":"hostname"
               }
            ]
         },
         "volumes":[
            {
               "containerPath":"/zfs",
               "hostPath":"/net/zfs1/export",
               "mode":"RW"
            }
         ]
      },
      "resources":{
         "cpus":2.0,
         "memoryMb":128,
         "numPorts":0,
         "diskMb":0
      }
   },
   "message":"BDD Test Deployment"
}
```

And the deploy works, but the JSON for the deploy that the UI shows is this:

```json
{
    "deployId": "MyTestDeploy.939460",
    "requestId": "MyTestRequest-938634",
    "deployResult": {
        "deployState": "SUCCEEDED",
        "message": "Request not deployable",
        "deployFailures": [],
        "timestamp": 1487357943844
    },
    "deployMarker": {
        "requestId": "MyTestRequest-938634",
        "deployId": "MyTestDeploy.939460",
        "timestamp": 1487357939551,
        "message": "BDD Test Deployment"
    },
    "deploy": {
        "requestId": "MyTestRequest-938634",
        "id": "MyTestDeploy.939460",
        "command": "",
        "containerInfo": {
            "type": "DOCKER",
            "volumes": [
                {
                    "containerPath": "/zfs",
                    "hostPath": "/net/zfs1/export",
                    "mode": "RW"
                }
            ],
            "docker": {
                "image": "pdocker.valkyrie.net/odc/generic-launcher-svc-test-app:latest",
                "privileged": false,
                "network": "HOST",
                "portMappings": [],
                "forcePullImage": false,
                "parameters": {}
            }
        },
        "resources": {
            "cpus": 2,
            "memoryMb": 128,
            "numPorts": 0,
            "diskMb": 0
        },
        "env": {
            "SVC_ENVIRONMENT": "ci",
            "VERSION": "1.0.0-1"
        }
    }
}
```

parameters is empty and no dockerParameters is shown. I just want to be clear before I ask for Singularity to be upgraded on my cluster. Thanks.

**Comment by ssalinas** [comment]
Back in `0.9.0` you can set them, it is just `parameters` which is a Map<String, String>. `dockerParameters` didn't come along until later

**Comment by billwright** [comment]
I tried parameters and they weren't being listed in the JSON after the successful deploy. I thought the above discussion was telling me I needed to use dockerParameters. So, what's the JSON look like that will work? Something like this:

```json
 "docker":{
            "network":"HOST",
            "image":"pdocker.valkyrie.net/odc/generic-launcher-svc-test-app:latest",
            "parameters": {
                  "user":"616573731",
                  "hostname":"my-singularity-app"
            }
         },
```

**Comment by ssalinas** [comment]
correct

**Comment by petrovicboban** [comment]
I am using 0.13.0 and I dont have issues with docker parameters. It works as expected.  
![image](https://cloud.githubusercontent.com/assets/13204754/23459806/5a752646-fe82-11e6-9ffc-def39fd078ab.png)
