### ISSUE TITLE
Specify docker container name

### ISSUE THREAD

**Issue by vinhtr** [HubSpot/Singularity#1422]
Is it possible to override the default docker container name using dockerParameters in SingularityDockerInfo? The following doesn't seem to work

```
    "containerInfo": {
      "type": "DOCKER",
      "docker": {
        "dockerParameters": [
          {"key": "name", "value": "foo"}
        ]
      }
```

instead what I'm seeing for a name is something like,

`mesos-c1352c37-ef07-420e-989e-24d6ba9c15d5-S12.7cd6c0c...`

**Comment by ssalinas** [comment]
Currently this is not supported by mesos, see https://www.mail-archive.com/user@mesos.apache.org/msg05869.html

**Comment by petrovicboban** [comment]
Use singularity executor, and set name in docker parameters field.

**Comment by ssalinas** [comment]
@petrovicboban , no the singularity executor uses it's own name as well, specifying the name in docker parameters would mean you'd be setting --name twice on the command line to create the contianer

**Comment by petrovicboban** [comment]
yes, but looks like docker engine accepts the last --name in command line, and thats what is happening if you specify name as docker parameter in deploy page.
