### ISSUE TITLE
Executor cleanup can't connect to https service endpoint

### ISSUE THREAD

**Issue by petrovicboban** [HubSpot/Singularity#1430]
Hi,  
this is imposible right now.   

singularityHosts:
- host:port
- host:port

Cleaner tries to connect to http://host:port

I have singularity services behind https nginx proxies, and services themselves are binded to localhost, so cleaner cant connect to services.

**Comment by ssalinas** [comment]
Yeah, the client defaults to http at the moment, we can update this
