### ISSUE TITLE
Overlay network and container name issue 

### ISSUE THREAD

**Issue by petrovicboban** [HubSpot/Singularity#1439]
I set up overlay network, so containers can communicate between hosts using containers names. I can set up containers name and network by using docker parameters on deploy UI page. Obviously, two containers in this setup cannot have the same name.  
Container starts ok, with set network and name, and thats ok, but when task is killed or bounced, issue arises: singularity first try to bring new container (with the same name as old), and then clean old container. That produces error on new container:  
```
Error response from daemon: service endpoint with name example_name already exists
```
After this, request goes to cooldown state, and in that interval, cleaning of old task is done, so container finally starts on some host (including original host)

The worst thing is that singularity leaves failed container on host in 'Created' state, and doesnt even try to remove it. That effectively prevents that container to be started on that host, until it is manually  removed or renamed.

Is there a way for singularity to wait until full clean of old task before bringing new one?

**Comment by ssalinas** [comment]
The task is being left in created state _because_ you are overriding the name. The executor does it's best to clean things up, but it expects them to be named a certain way same as mesos does with the mesos- prefix on all names).

If you need to anticipate the name, singularity executor will always name it as `se-(task id)`.

As for the overlay network piece, I haven't worked with that at all yet personally, so I'm not sure what's involved there. It's very possible we don't quite have the feature set to support it in Singularity yet.

I'm going to close this one, but if there are specific features you are missing to implement what you are looking for, feel free to file an issue with more details

**Comment by petrovicboban** [comment]
Thanks for answer.  
Overlay network is global network between hosts, and also works as name discovery service allowing containers that are in overlay network to communicate by using container names. Since singularity changes container names on every task killl or request bounce, we cant use container names as connection endpoints in dockerized service config, and this extremely usefull  feature of docker engine is lost that way.
