### ISSUE TITLE
What can cause request to exit cooldown?

### ISSUE THREAD

**Issue by bydga** [HubSpot/Singularity#1441]
This just happened to us - a cron request that has been running for some period (it fails from time to time, but thats fine) suddenly exited cooldown without any task being run or new deployment made.. see the screenshot: http://prntscr.com/egl36k

Any idea what could have caused this?

**Comment by ssalinas** [comment]
Cooldown has a time associated with it. See the docs at http://getsingularity.com/Docs/reference/configuration.html#cooldown
