### ISSUE TITLE
Legacy support for URIs as an array of strings changes extraction behaviour

### ISSUE THREAD

**Issue by demobox** [HubSpot/Singularity#1460]
The change in f68615f9d3 from `uris` being an `Array<String>` to `Array<SingularityMesosArtifact>` added a backwards-compatibility option to convert the strings to  `SingularityMesosArtifact`s.

That code has since been removed, but the equivalent migration (?) code that converts existing Deploys to work with 0.14.0 seems to have the same behaviour. This breaks Deploys that use compressed artifacts, since the previous behaviour was for such artifacts to be automatically extracted.

Would it be possible to change that migration logic to set `extract` to `true` for legacy URIs? Are there other suggestions for how to migrate a set of existing Deploys when moving to 0.14.0?

**Comment by ssalinas** [comment]
Updated in 0.14.1, thanks for letting us know

**Comment by demobox** [comment]
> Updated in 0.14.1, thanks for letting us know

Wow, that was quick - many thanks!
