### ISSUE TITLE
What does "Request not deployable" mean?

### ISSUE THREAD

**Issue by billwright** [HubSpot/Singularity#1484]
I don't get any errors when running my request, but this text disturbs me, as it seems like an error. It appears in the JSON of the deploy for the request, so it seems to be contradicting itself:

```json
{
    "deployId": "1",
    "requestId": "testz",
    "deployResult": {
        "deployState": "SUCCEEDED",
        "message": "Request not deployable",
        "deployFailures": [],
        "timestamp": 1491004331913
    },
```

Looking at the code in class SingularityDeployChecker.java, is just as confusing:

```java

if (!request.isDeployable()) {
LOG.info("Succeeding a deploy {} because the request {} was not deployable", pendingDeploy, request);
return new SingularityDeployResult(DeployState.SUCCEEDED, "Request not deployable");
}
```

So if the request isn’t deployable, then we succeed in deploying?

I just want to understand this terminology.

Thanks,
Bill

**Comment by ssalinas** [comment]
'Not deployable' just means that we don't need to monitor the deploy. For example, a service or a worker has checks that need to be run, and we ensure new instances are started before the old ones are shut down.

But, in the case of an ON_DEMAND, RUN_ONCE, or SCHEDULED request, there isn't anything to check on the deploy, the new settings just apply to the next task that is run.
