### ISSUE TITLE
Command not found when running a docker image

### ISSUE THREAD

**Issue by billwright** [HubSpot/Singularity#1485]
I'm running Singularity 0.9.0. I have a Docker image built from this Dockerfile:

```docker
FROM python:2.7

RUN pip install Flask==0.11.1

WORKDIR /app
COPY app /app

CMD ["python", "service.py"]
```

There are three files in the /app directory, all python files. They are named app.py, service.py, and a helper file zfs_checking.py. The app.py file
just checks for zfs directory mounts and prints out a status message. That’s it. Running it looks like this:

```bash
BillWright-Mac:test-docker-image bill.w.wright$ docker run -it 444919eee6aa python app.py
/zfs is NOT mounted
```

If I ran that image without the command after it, it would start up a service that could give you the same results if you hit the base endpoint:

```bash
BillWright-Mac:test-docker-image bill.w.wright$ docker run -it 444919eee6aa 
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
^CBillWright-Mac:test-docker-image bill.w.wright$ 
 ```

Using the Singularity UI, I create the request and the deploy, which is then represented by this JSON:

```json
{
    "deployId": "1",
    "requestId": "testz",
    "deployResult": {
        "deployState": "SUCCEEDED",
        "message": "Request not deployable",
        "deployFailures": [],
        "timestamp": 1491004331913
    },
    "deployMarker": {
        "requestId": "testz",
        "deployId": "1",
        "timestamp": 1491004329672
    },
    "deploy": {
        "requestId": "testz",
        "id": "1",
        "command": "python app.py",
        "containerInfo": {
            "type": "DOCKER",
            "volumes": [
                {
                    "containerPath": "/zfs",
                    "hostPath": "/net/zfs1/export",
                    "mode": "RW"
                }
            ],
            "docker": {
                "image": "pdocker.valkyrie.net/odc/test-docker-image:1.2.0-2",
                "privileged": false,
                "network": "HOST",
                "portMappings": [],
                "forcePullImage": false,
                "parameters": {}
            }
        },
...
```

When I try to run this request I get this error in the standard error log:

```bash
docker: Error response from daemon: Container command 'python app.py' not found or does not exist..
```

The call to docker (example above) seems to indicate that the command is there. Is this a bug or a user error?

Thanks,
Bill

**Comment by petrovicboban** [comment]
Can you check PATH env variable and print it before executing command in container?

**Comment by ssalinas** [comment]
Yeah, I'd check on your side first, especially since it is mesos executor. The only other thing I can think of is that we did make some improvements as to when `shell` mode is set to true/false in later Singularity versions, that may also be impacting how the mesos docker executor is running the command (very possible you need the full path to `python` as @petrovicboban hinted at)

**Comment by ssalinas** [comment]
Going to close this one for now. If it seems that this ends up being a Singularity issue and is still present in more recent versions feel free to reopen

**Comment by billwright** [comment]
I solved my problem by setting the parameter "terminal" to "false." Very unintuitive, but it worked. If this is always required for the command to work, then perhaps this value should be forced to false in this situation...
