### ISSUE TITLE
Missing image in the documentation

### ISSUE THREAD

**Issue by PotHix** [HubSpot/Singularity#1508]
![image](https://cloud.githubusercontent.com/assets/14836/25207569/08cf0f56-2546-11e7-8cba-59d21bcf1d21.png)

There is a broken image on the main page of the documentation. The image is in the repository (https://github.com/HubSpot/Singularity/blob/master/Docs/images/singularity.png) but it's not in the deployed version (http://getsingularity.com/Docs/images/singularity.png).

**Comment by ssalinas** [comment]
image is fixed now
