### ISSUE TITLE
Resource Usage bug

### ISSUE THREAD

**Issue by petrovicboban** [HubSpot/Singularity#1509]
![image](https://cloud.githubusercontent.com/assets/13204754/25225139/bf191a70-25c0-11e7-9ae0-91f3c28b5b5f.png)

I didn't set 0 CPUs on deploy, so I'm not sure how should I interpret informations on the picture.

**Comment by petrovicboban** [comment]
I hope this will be resolved with https://github.com/HubSpot/Singularity/pull/1592

**Comment by ssalinas** [comment]
@kwm4385 can you double check if this is still the case? The 0 cpus case can be set when cpu isolation isn't being used in the cluster, so no cpus need to be allocated. Not sure if it makes more sense to show the cpus used (hard to determine what the upper bound to make the bar should be), or just hide the box

**Comment by kwm4385** [comment]
Since the usage is still relevant, I should just be able to hide the bar and just show the utilization. I'll copy this issue when I fix that.

**Comment by kwm4385** [comment]
This is now addressed in #1592
