### ISSUE TITLE
singularity holding offers for long time

### ISSUE THREAD

**Issue by bydga** [HubSpot/Singularity#1532]
Hey, we just noticed (we are running singularity on one cluster together with marathon) that sometimes marathon takes ages to deploy new app. After inspecting whats wrong, I found out that singularity keeps all offers and they are visible in the "outstanding offers" tab in the mesos-ui: http://prntscr.com/f5r2pr.

Seems like the only way marathon can deploy something is, when the offers times-out, mesos sends to both frameworks new ones and marathon catches his breath.. and then Singularity eats everything again.. 

Is there some setting I'm missing or is it an expected behavior?

mesos: 1.2.0
singularity 0.14.1
marathon: 1.4.2

**Comment by PtrTeixeira** [comment]
See also [PR 1402](https://github.com/HubSpot/Singularity/pull/1402#issuecomment-299815613); resolved by PR #1529.

**Comment by ssalinas** [comment]
This is the same as the issue referenced in https://github.com/HubSpot/Singularity/pull/1402#issuecomment-299815613 . You can set `cacheOffers: false` in your config yaml to return to the previous behavior. https://github.com/HubSpot/Singularity/pull/1529 adds the docs for this and will turn the offer cache off by default

**Comment by ssalinas** [comment]
@PtrTeixeira beat me to it ;)

**Comment by bydga** [comment]
oh, thanks somehow i searched only issues and missed the discussions in the PRs, thanks for pointing out :)
