### ISSUE TITLE
taskExecutionTimeLimitMillis not hooked up in ui

### ISSUE THREAD

**Issue by bydga** [HubSpot/Singularity#1550]
I create a cron-request, set taskExecutionTimeLimitMillis (in the UI to 1 minute), run a (docker) task that takes 10mins to complete and the task doesnt end after the desired 1 minute. Am i doing something wrong?

http://prntscr.com/fbim25

**Comment by bydga** [comment]
Ha! i just found out that the UI field `Maximum task duration` is actually being sent on the backend as a field `scheduledExpectedRuntimeMillis`: http://prntscr.com/fbixpq

Which i have no idea what that should be. But anyways, even when i edit the request manually through API and sent a proper field `taskExecutionTimeLimitMillis`, the task still keeps running unless it finishes itself :(

**Comment by bydga** [comment]
ping

**Comment by ssalinas** [comment]
@bydga `scheduledExpectedRuntimeMillis` is an expected runtime used in notifications. It helps determine if a scheduled task is overdue or not. `taskExecutionTimeLimitMillis` is the hard limit. It's likely that one didn't get added to the ui page when the field was added.

I can attempt to get a fix in to go with 0.16 and include the field in the UI + update the descriptions of the names to be more clear. If you need it sooner PRs are always welcome as well (code lives [here](https://github.com/HubSpot/Singularity/tree/master/SingularityUI/app/components/newDeployForm) for that form)

**Comment by bydga** [comment]
Cool! There was another thing that actually confused me and led me to an assumption that the `taskExecutionTimeLimitMillis` is not working at all. There is https://github.com/HubSpot/Singularity/blob/master/Docs/reference/configuration.md#pollers `checkJobsEveryMillis` config option set up to 10mins. I always set up a task with execTimeLimit=1minute and after 5mins it was still running - so I expected its not working at all. I just didnt hit the poller interval. 

So if anyone in future is having simmilar problem, here's explanation :) ^^

**Comment by ssalinas** [comment]
Makes sense. When we wrote it, the purpose was more about catching stuck tasks that were running for many hours or days past when they should have, so a slower poller interval made more sense. Glad you found the solution
