### ISSUE TITLE
Scheduled Tasks page updates

### ISSUE THREAD

**Issue by wsorenson** [HubSpot/Singularity#158]
<code> /singularity/v2/tasks/scheduled </code>

calls the endpoint:

<code> singularity/v2/api/tasks/scheduled </code>

It should probably add some property filtering, like:

<code> singularity/v2/api/tasks/scheduled?property=pendingTask </code>

This gives you all the data you need to render that table.

On the other hand, the JSON button will now not have enough data. Change the JSON button to actually fetch the data about that scheduled task instead.

Table could be better also:

- Show pending_type in the table
- Show deploy_id in the table
- It should probably link to the Request (since this is a future task it can't link to a task)

**Comment by benrlodge** [comment]
WIP: https://github.com/HubSpot/Singularity/pull/488
