### ISSUE TITLE
'Requests groups' feature documentation

### ISSUE THREAD

**Issue by petrovicboban** [HubSpot/Singularity#1602]
Hi,  
is there any documentation regarding 'requests group' feature, except documentation for [API calls](http://getsingularity.com/Docs/reference/apidocs/api-groups.html)  
I mean, I don't know what is it used for, what was the idea behind the feature.  

I need the possibility to start/stop a group of requests as a whole, so it comes to my mind that this feature can handle that, but I can't find any documentation for it.

**Comment by ssalinas** [comment]
The request groups is more for logically grouping things in the UI that actually operating on a group of them. For example, if you put two requests in the same group you'd get a tabbed ui page like:

<img width="1486" alt="screen shot 2017-07-24 at 10 03 48 am" src="https://user-images.githubusercontent.com/6034439/28527084-7b6db4b6-7057-11e7-96c4-a6ab4fb4e56a.png">

You can operate on all requests in a group via the ui, but behind the scenes it is just making multiple api calls. If you want to start adding request groups, you can `POST` a [`SingularityRequestGroup`](https://github.com/HubSpot/Singularity/blob/master/SingularityBase/src/main/java/com/hubspot/singularity/SingularityRequestGroup.java) (basically an id for the group + list of request ids) to the `/api/groups` endpoint

Will leave this open to add some documentation on what the features does though.

**Comment by petrovicboban** [comment]
Thanks for explanation.   
I assign couple of requests to the same group, but I don't see any url which would give me group page, like you showed in the answer.  
I'm still on 0.13. Does it exist there, or it's added in later, because I can't see mentioning that url in next releases?

**Comment by ssalinas** [comment]
Request groups was added in 0.12

**Comment by petrovicboban** [comment]
I found that info. But what I didn't find is url on UI that I can use to view groups (part of your sreenshot in your answer).  
But maybe you prefer that singularity users dig source code in search of useful information.  I tried to do that way, pick something from [here](https://github.com/HubSpot/Singularity/pull/1130/commits/d4b4425fbeb5606ca7ab1273f5264546153afb45) but still no luck,  /singularity/groups on UI returns 404.

**Comment by ssalinas** [comment]
In the ui the path should be `(ui base)/group/(group id)`. If a request is part of a group, it should have a link to that page in the upper left of the request detail page

**Comment by petrovicboban** [comment]
Hi,  
API calls work fine. However, there is no any link in UI for accessing groups. I have to manually enter `(ui base)/group/(group id)`.  
Also, there is no possibility to add, remove or modify groups using UI.

**Comment by ssalinas** [comment]
The link may have been added in a later version. We do have plans to expose the groups in the ui more in upcoming releases as well

**Comment by ssalinas** [comment]
There are now nicer links for groups in the UI in recent releases. The UI allows some bulk actions, but is still just making multiple calls. We don't have any plans to make bulk actions on the backend at the moment. So going to close this one for now
