### ISSUE TITLE
Canary releases/deployments

### ISSUE THREAD

**Issue by lenfree** [HubSpot/Singularity#1607]
Hi guys, is it possible to do canary releases/deployments ATM? If not, is there a plan to add this feature? 😄

**Comment by ssalinas** [comment]
Singularity has a concept of [incremental deploys](http://getsingularity.com/Docs/features/incremental-deploys.html) that can be used for this. With an incremental deploy, you can deploy `x` out of `y` instances for a request and then have it continue either after a set time or by a user-triggered action from the ui. Is this what you were generally looking for?

**Comment by lenfree** [comment]
@ssalinas cool! this is what I am was looking for. Thanks!
