### ISSUE TITLE
Singularity failing to create slave on Rancher with RHEL 7 instances

### ISSUE THREAD

**Issue by mkum9469** [HubSpot/Singularity#1624]
I'm trying to deploy Singularity on Rancher with a set of RHEL 7.3 (3.10.0) instances. Everything else works fine but the slave node keeps failing to start giving the following error.

> Failed to create a containerizer: Could not create MesosContainerizer: Failed to create launcher: Failed to create Linux launcher: Failed to determine the hierarchy where the subsystem freezer is attached

How can I resolve this?

**Comment by ssalinas** [comment]
Hi @mkum9469 , it seems that is a problem with the configuration of mesos slave itself, not with Singularity. There is a similar thread I found [here](https://github.com/eBayClassifiedsGroup/PanteraS/issues/142) that might be able to help you diagnose the error. That thread is specifically ubuntu-related, but I'm guessing similar isolation/cgroups settings apply.

**Comment by ssalinas** [comment]
Going to close this out since it is not specifically Singularity-related, but feel free to send questions to the mailing list on the README and someone in the community can likely help you out 👍

**Comment by mkum9469** [comment]
This your link and my answer to my question on StaskOverflow says to add some commands into `restricted/host`. But where I should do this? Can I put in on `docker-compose.yml`? 
https://stackoverflow.com/a/46646733/1190184

**Comment by ssalinas** [comment]
That depends how you are running the mesos-slave/mesos-agent process. Those are arguments for mesos, not for singularity.

**Comment by ssalinas** [comment]
I just realized you may be talking about the docker-compose in this repo. That docker-compose is mainly meant for trying out singularity on your local machine, not necessarily for production use. If you need to add those areguments/environment variables, it would go in this section https://github.com/HubSpot/Singularity/blob/master/docker-compose.yml#L19-L31

**Comment by mkum9469** [comment]
Oh! I see. How are we supposed to run Singularty for production, the idea way?

**Comment by ssalinas** [comment]
You can use the same images from the docker compose yaml, but you'll need to configure the mesos agents to fit your own needs. We provide a mesos slave image preloaded with out custom executor and a few basic libraries, but companies like mesosphere also provide mesos agent images you can use. Generally they can be configured by environment variables or arguments
