### ISSUE TITLE
Web interface JS caches forever (or just too long)

### ISSUE THREAD

**Issue by carlf** [HubSpot/Singularity#1641]
I have found on upgrade, that a shift-reload is required to reload the javascript. When I do a curl, I find the following:

```
$ curl -I http://singularity/static/js/app.bundle.js
HTTP/1.1 200 OK
Date: Wed, 01 Nov 2017 23:55:10 GMT
Last-Modified: Fri, 04 Aug 2017 17:35:54 GMT
ETag: "17e67d2bec249a010b97c4af40cee9ad"
Content-Type: application/javascript
Content-Length: 2112229
```

That Last-Modified is earlier than when I upgraded to singularity 0.16.2 so it never gets loaded after an upgrade. It's not a huge deal but I usually field 10 or so users asking what's wrong with singularity after every update.

**Comment by ssalinas** [comment]
Thanks for letting us know. We can take a look at how dropwizard is determining the Last-Modified header. I'm guessing it is based on the time the build was done. We can maybe update it to me something like the time the current singularity process started
