### ISSUE TITLE
Launch Task on One Slave

### ISSUE THREAD

**Issue by DominikRobert** [HubSpot/Singularity#1652]
Hello I think there is a mistake in the "allowedSlaveAttributes" and the "requiredSlaveAttributes".

I have 4 nodes in Singularity and I want that some
task only run on a single node. I try it with a Request like this:
{
   "id": "Test",
   "requestType": "SERVICE",
   "requiredSlaveAttributes":
    {
        "rack": "test"
    }
}
And like this:
{
   "id": "Test",
   "requestType": "SERVICE",
   "requiredSlaveAttributes":
    {
        "rackid": "test"
    }
}

My Mesos-Slave shows following output:
 "id": "03d51d1a-4398-4ade-8af4-b72b470d8874-S1",
            "hostname": "docker1",
            "port": 5051,
            "attributes": {
                "rackid": "test",
                "rack": "test"
            },

So I think, they should accept this attributes and just launch it on
the nodes which have these attributes. But it don't start. Its always a
pending Deploy. I think they didn find the attributes, but what can I
do that they find and only launch on this nodes?

my /etc/mesos-slave/attributes file:
tried with:
    rackid:test;
    rack:test
And with:
    rackid:test
    rack:test

The Racks are displayed in Singularity correctly just the launch on the
correct node doesn't work.

docker version
Docker version 17.09.0-ce, build afdb6d4

Singularity Version: 0.17.0

Can you help me?

**Comment by ssalinas** [comment]
It seems like you have your attributes set correctly on your mesos slave. The first thing that comes to mind for me is that there may not be room on that slave to launch the task. If you turn the logging to TRACE level you should be able to see some evidence of this in the Singularity output. There will be logs like:

```
Task requires slave with attributes {} ...
```
for offers from slaves that do not match attributes, and ones like
```
Ignoring offer on host {} with roles {} on {} for task {}; matched resources: {}, slave match state: {}
```
if the slave matches the attributes but doesn't have sufficient resources for the task.

TRACE logging can be turned on by adding this to your config yaml
```
logging:
  loggers:
    "com.hubspot.singularity" : TRACE
```

**Comment by ssalinas** [comment]
Closing for lack of response, feel free to reopen if you are still experiencing issues
