### ISSUE TITLE
UI broken in 0.18.1

### ISSUE THREAD

**Issue by jaredstehler** [HubSpot/Singularity#1670]
After upgrading to 0.18.1 the singularity UI is no longer working, returning 404's for static web assets. It seems to be just urls like `/singularity/static/*`; the api urls seem to be functional.

I had previously been running on a fork version: https://github.com/intellifylearning/Singularity/compare/master...HubSpot:master

**Comment by jaredstehler** [comment]
It appears that the static assets are missing from the build artifact:

here's what I see with a `jar tvf` of my forked build:
```     0 Sun Nov 26 08:28:16 EST 2017 assets/static/js/
2187626 Sun Nov 26 08:28:16 EST 2017 assets/static/js/app.bundle.js
10527043 Sun Nov 26 08:28:16 EST 2017 assets/static/js/app.bundle.js.map
639573 Sun Nov 26 08:28:16 EST 2017 assets/static/js/vendor.bundle.js
4639107 Sun Nov 26 08:28:16 EST 2017 assets/static/js/vendor.bundle.js.map
```

and I don't see those in `SingularityService-0.18.1-shaded.jar` of the broken build.

**Comment by ssalinas** [comment]
Looking into this today. Hoping to have to new fixed release out by EOD

**Comment by ssalinas** [comment]
fixed on https://github.com/HubSpot/Singularity/releases/tag/Singularity-0.18.2
