### ISSUE TITLE
Healthchecks are not working properly in 0.18.2

### ISSUE THREAD

**Issue by yuriy-filatov** [HubSpot/Singularity#1691]
Hullo.
We're running Singularity 0.18.2 to orchestrate our mesos jobs.
After upgrade from 0.17.x we've noticed weird behaviour of existing healthchecks - all our jobs now fail to pass second test and get killed with "OVERDUE_NEW_TASK - Task did not become healthy after 10:00.000".
We've tried to change URI (one of our suggestions was in passing 302 to healthcheck) and to increase timeouts  - no luck. So weve disabled healthchecks completely.

Any possible solutions here?
Thanks.

**Comment by ssalinas** [comment]
Hmm, there weren’t any major updates to healthchecks in this release. Some information to help debug:

- Are you seeing the health checks attempted at all? On the task page at the bottom there is a healthchecks section that will list the results of each attempt (for a task that failed checks it only saves the most recent failures)
- if checks are being attempted, what type of failures are they showing?
- if checks are not seen on the task page, are there exceptions in the Singularity log related to running health checks?

**Comment by yuriy-filatov** [comment]
Here's our configuration:
`  healthcheck:
    intervalSeconds: 10
    maxRetries: 20
    startupDelaySeconds: 240
    uri: /jobs/`

As for your questions. Here are HCs we're able to see in UI:
`Beginning 240s after Task enters running, wait a max of 45s for app to start responding, then hit /jobs/with a 5 second timeout every 10 second(s) until:
    HTTP 200 is recieved
    20 retries have failed. `
First one is green, second one - red.
We've also checked firewall/connections inside cluster - everything's ok.

Ref logs - we've got 200k+ messages to parse - can you please poing me to proper error response? I'll check.

**Comment by ssalinas** [comment]
Ok, if the first of the checks was green that should mean it passed. Is that the case for all tasks? One possibility is that the healthcheck passed slightly too late (passed the 10 min limit). I'd be surprised if this was the case for all tasks then. You can check the timestamp on the `TASK_RUNNING` task update and compare to the timestamp on the last (successful) healthcheck to see if those are more than 10 min apart.

In the logs the relevant lines to help figure out the case above would be at debug level, and from the `SingularityDeployHealthHelper` or `SingularityNewTaskChecker` class. The log line should also contain the task id to help filter it down. Would be helpful to take a look at those to see what Singularity was seeing when checking health check results

**Comment by ssalinas** [comment]
Closing for lack of response, feel free to reopen if you are still experiencing issues

**Comment by yuriy-filatov** [comment]
@ssalinas I'll be back on this shortly, sorry for the delay.
