### ISSUE TITLE
Components update order

### ISSUE THREAD

**Issue by petrovicboban** [HubSpot/Singularity#1712]
In which order should components (service, executor, etc) be updated?
Is it safe to first update executor and other slave components and update service after it, or should it be done in opposite direction?
Specifically, our plan is to update from 0.13 to 0.18.2

**Comment by ssalinas** [comment]
This is already documented in the release notes. I would recommend reading http://getsingularity.com/Docs/features/mesos-1.html since jumping to 0.18 means an upgrade to mesos 1
