### ISSUE TITLE
Driver not started in 0.18.2

### ISSUE THREAD

**Issue by petrovicboban** [HubSpot/Singularity#1729]
We have 0.17.0 cluster, and I updated one of the instances (db11). Picture bellow shows 'Not started' in Scheduler Client Status, but it works.

![image](https://user-images.githubusercontent.com/13204754/36453226-a16dcdd6-1697-11e8-8bf0-9cc21e5bf096.png)

Is that expected since there is amove to mesos http api?

**Comment by ssalinas** [comment]
This is a dupe of the issue in https://github.com/HubSpot/Singularity/issues/1641 , hard refresh the UI and you'll see the newer table with updated values for mesos http api
