### ISSUE TITLE
Aggregated logs

### ISSUE THREAD

**Issue by petrovicboban** [HubSpot/Singularity#1733]
Hi,
`View Aggregated Logs` allows combined view of only `stdout`. That's pretty much useless if singularity executor is in use. Is there a way to follow tail of `service.log` inside of each task instance?  

![image](https://user-images.githubusercontent.com/13204754/36529858-dfa5af38-17b9-11e8-9666-4355ded4699a.png)

**Comment by ssalinas** [comment]
In the `ui` portion of SingularityService yaml, you can set `runningTaskLogPath: $TASK_ID/service.log` to update all of the defaults for these types of links to be the service.log instead

**Comment by ssalinas** [comment]
Right now this is a global
