### ISSUE TITLE
Paused request should remain paused after new deploy

### ISSUE THREAD

**Issue by yuriy-filatov** [HubSpot/Singularity#1737]
Hey there.
I'll try to explain the cause of this request.
We're running Singularity 0.18.2 to orchestrate our mesos jobs in Production.
We have 200+ requests, several of them are paused.
Sometimes we have to roll out changes to all existing jobs - it can be either new link to some new endpoint or any other dynamic data. 
We're experiencing quite massive pita in current setup - all paused requests become active immediately after new deploy.
I do understand that this request might broke internal state machine, but is it possible to add override key in the settings somewhere? This will definitely save us some time and hair.
Thanks.

**Comment by ssalinas** [comment]
The reason we don't have this currently is more around the health checks for a request. If a request is paused and we accept the deploy as a success, we have no verification that the new deploy is viable/will work when unpaused. However, we have had a few requests for similar functionality internally, so it's definitely something we could look into supporting in future releases

**Comment by yuriy-filatov** [comment]
Well, that's why we have deploy checks, eh. If request is non-deployable - it should not be sent to Singularity at all.

Please let me know if this will be included into some incoming release.

Thank you.

**Comment by yuriy-filatov** [comment]
Hey @ssalinas 
Hope my message finds you well.
I've tried to use 'allowDeployOfPausedRequests' -- but it doesn't seem to work.
I've added 'allowDeployOfPausedRequests=true' into startup script (along with working 'hostname' option for example) -- nothing changed in s9y behavior.
Can you please check/explain how to use that option?

**Comment by ssalinas** [comment]
Hmm, I can get it to work on our staging env. When you POST the deploy, are you getting the conflict message still like before? First guess is that the configuration option isn't being picked up for some reason. You guys use the docker image to run Singularity correct? Can try and confirm with that as well to see if it's maybe the jar in the docker image is incorrect or something

**Comment by yuriy-filatov** [comment]
I've verified s9y shaded jar md5 inside running container - it's definitely 0.19.2.
I've tried to pass options through:
- startup shell script insode docker which we use for numerous dynamic options which differ from env to env alike 
``#!/bin/bash
exec /usr/bin/java -Ddw.ui.title="${UI_TITLE}" -Ddw.ui.navColor="${UI_NAVCOLOR}" -Ddw.hostname=${HOSTNAME} -Ddw.allowDeployOfPausedRequests=true -jar SingularityService.jar server singularity-config.yaml``
- plain option in singularity-config.yaml
None of these work for us.

What I expect to see:
I'm navigating to Requests -> some_request_here -> Pause -> State changes to Paused in Request history, so request is paused -> posting new deploy for this request -> New deploy ID in deploy history along with all changes in activeDeploy -> request state remains paused

What I see:
... -> request state changes to unpaused and scheduled.

Is there a hook to report all 'active' configuration keys inside s9y?
Thanks.

**Comment by ssalinas** [comment]
Ah, are you specifying the 'deploy to unpause' option on the deploy request? That is the only way I've been able to reproduce this behavior

**Comment by yuriy-filatov** [comment]
Oh, makes sense -- that might be one of bells and whistles inside of our deployer.
I'll check and get back to you shortly.

**Comment by yuriy-filatov** [comment]
Well, I've found and removed related code in our deployer.
And everything is working now.
Thanks! Sorry for the panic.
