### ISSUE TITLE
Health Checks issue

### ISSUE THREAD

**Issue by petrovicboban** [HubSpot/Singularity#1739]
If I want to deploy new task using UI, for request type WORKER, ui only allows setting timeout after task is considered healthy.  
![image](https://user-images.githubusercontent.com/13204754/36740464-c2a5ac30-1be2-11e8-867b-09e389c39243.png)

However, my deploy fails to pass healthcheck:  

![image](https://user-images.githubusercontent.com/13204754/36740576-1ed90678-1be3-11e8-8693-8edcf7b50cc1.png)

What does healthcheck check after all? That's just a worker, not listening to any port.

**Comment by ssalinas** [comment]
What does the Healthchecks portion of the UI look like for that task? Is Singularity attempting http health checks?

**Comment by petrovicboban** [comment]
Yes it does, but I didn't set that anywhere. However it is there:  

![image](https://user-images.githubusercontent.com/13204754/36740967-3aba950e-1be4-11e8-8220-3e8d9ad55834.png)

Obviously, there is no uri or port defined there so it fails with:  

![image](https://user-images.githubusercontent.com/13204754/36741023-5c653d08-1be4-11e8-947e-95ca55714cee.png)


This is service version 0.17
Request was created while it was version 0.13, and it's upgraded later.

**Comment by petrovicboban** [comment]
I'm not sure if healthcheck existed there before upgrade to 0.17,  or it was just default value, ignored probably. But this is now serious issue, since we have couple of hundreds of WORKER requests.

**Comment by ssalinas** [comment]
Is there a `healthcheckUri` in your deploy json as well? I'm looking through to find where this could have gotten initialized in that way, and the newer `HealthcheckOptions` object only gets initialized from the older settings when `healthcheckUri` is present, which would point to the workers having healthchecks to start with

**Comment by petrovicboban** [comment]
I turned off healthchecks on request level, so I can create new deploy now:  
![image](https://user-images.githubusercontent.com/13204754/36741568-c3c7292e-1be5-11e8-9fbd-76e2bda6bf3c.png)


And for your answer, there is no `healthcheckUri ` in deploy json.

**Comment by ssalinas** [comment]
Ok, this sounds like it is an issue with the UI form/validation then, which should not be sending in the `healthcheck` section at al for this particular case. Do you generally do all deploys via the UI, or via other cli/api tools?

**Comment by ssalinas** [comment]
Yes, confirmed that the UI is sending this in incorrectly. We can implement a fix for the UI and deploy validation. Shouldn't be too hard to backport to an 0.17.1 release

**Comment by petrovicboban** [comment]
Thanks a lot for help.  
We use custom developed apps for creating new requests and deploys, but sometimes, we do it manually.

**Comment by ssalinas** [comment]
This should only be an issue for deploys via the UI, otherwise the normal flow will work correctly. For reference, Singularity will attempt healthchecks as long as the `healthcheck` field is present. I am adding an extra piece of validation to make sure all needed fields are present on that object when it is specified. I have a fix for the UI now locally as well. Can probably have 0.17.1 up later today or tomorrow

**Comment by ssalinas** [comment]
fix released in 0.17.1 and will be merged into master/0.19.1 once we get it through our other environments. Just hit release in sonatype, so the 0.17.1 jars should be up shortly

**Comment by petrovicboban** [comment]
Thanks a lot for improving the product!
