### ISSUE TITLE
Missing 0.19.0 on docker hub

### ISSUE THREAD

**Issue by carlf** [HubSpot/Singularity#1742]
We were working on some integration tests with 0.19.0 and found that there is no release here for the 0.19.0 release:

https://hub.docker.com/r/hubspot/singularityservice/tags/

That repo has been very handy for testing things in the past. Should we expect an update now that 0.19.0 is out?

**Comment by ssalinas** [comment]
Odd, I thought I already pushed those images. Will get those up there in the morning 👍

**Comment by carlf** [comment]
:+1: thanks so much.

**Comment by ssalinas** [comment]
Just pushed up the images 👍
