### ISSUE TITLE
Mail notifications wrong recipient 

### ISSUE THREAD

**Issue by petrovicboban** [HubSpot/Singularity#1779]
Hi,
while we were on 0.13 version, Singularity was sending mail notifications (when task fails, for example) to addresses defined as request owners.  Now, on 0.17, we've noticed that it does not do so, but it sends mails to user who created request (string entered in dialog box if cookie is not present, I guess), which is breaking change for us.  
Is it a bug or a feature? :) Is there a way to make it how it was before?

**Comment by ssalinas** [comment]
All of the mail settings are configurable. During one of the releases in between there we also started email 'action takers' (i.e. person who might have triggered something like a create, bounce, pause, kill task, etc) _in additon_ to the owners. Check out the docs at http://getsingularity.com/Docs/reference/configuration.html#emails-list
