### ISSUE TITLE
Infinite spinner when browsing Tasks tab

### ISSUE THREAD

**Issue by yuriy-filatov** [HubSpot/Singularity#1789]
Hey there.
Faced subj in 0.19.2. Either navigate from Status -> Scheduled or directly from Tasks -> Scheduled just shows infinite spinner. 
Tasks -> Active is working fine. Please ping me for more details.

Any possible solutions? Thanks.

**Comment by ssalinas** [comment]
Have you checked the console log for errors? It's likely an api call failed or something similar, so it didn't get past the loading icon. Any other details on the error that occurred would be helpful

**Comment by subratbasnet** [comment]
This seems to be a UI/JS error.

Its looking for a property that is non existent. I have uploaded a screenshot below.

This happens with the latest (0.20.0) singularity as well. Can someone please confirm if this is an error?

![Uploading Tasks_-_Singularity_.png…]()

**Comment by subratbasnet** [comment]
![tasks_-_singularity__grepsr_](https://user-images.githubusercontent.com/3737047/41592439-4e534502-73dc-11e8-822f-ba7d902911d2.png)
Image above.

**Comment by yuriy-filatov** [comment]
Confirmed for 0.20.0

**Comment by ssalinas** [comment]
Fixed in 0.20.1
