### ISSUE TITLE
Deploy via GUI using Docker Container fails

### ISSUE THREAD

**Issue by mikebell90** [HubSpot/Singularity#1845]
Version: from master
On test local  cluster running mesos 1.40

If I create Deploy, choose Docker as the executor, set the docker container to mysql, networking to bridge, memory to 1gb, ports to 1, healthcheck uri to /, and skip healthchecks, my deploy fails.

Here is the equivalent curl
`curl 'http://localhost:7099/singularity/api/deploys' -H 'Accept: application/json' -H 'Referer: http://127.0.0.1:7099/singularity/request/kasksk/deploy' -H 'Origin: http://127.0.0.1:7099' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36' -H 'DNT: 1' -H 'Content-Type: application/json' --data-binary '{"deploy":{"id":"testing","executorType":"default","containerInfo":{"type":"DOCKER","docker":{"image":"mysql","network":"HOST"}},"resources":{"cpus":1,"memoryMb":1024,"numPorts":1,"diskMb":1024},"healthcheck":{"uri":"/","protocol":"HTTP"},"skipHealthchecksOnDeploy":true,"requestId":"kasksk","shell":true}}' --compressed`

The issue is the UI inserts shell:true even though I've not filled out any command line or arguments. (I want to just use the entrypoint).

Redeploying from CURL omitting the shell:true, succeeds.

**Comment by mikebell90** [comment]
I guess the question (I think) is, how can you deploy using the gui and not end up injecting shell:true?

Mostly this is just for q&d testing - all real stuff goes through the api

**Comment by ssalinas** [comment]
I have a branch locally for this. Adding `Shell` to the UI form

**Comment by mikebell90** [comment]
Danke!
