### ISSUE TITLE
Distributed / One-off Scheduled task

### ISSUE THREAD

**Issue by jloisel** [HubSpot/Singularity#187]
Is there a reason why scheduled tasks cannot be run on multiple instances ? Some scheduled tasks may not fit on a single instance, and be distributed by nature.

Another issue is due to the conversion between cron and quartz cron expression, it's not possible to design a one shot scheduled task. Or maybe i don"t have seen which cron expression to write to do this.

**Comment by ssalinas** [comment]
Closing this since there isn't currently an actionable item here.
