### ISSUE TITLE
Singularity Framework stuck in completed state on slave

### ISSUE THREAD

**Issue by jay-chin** [HubSpot/Singularity#1870]
Mesos-version: 1.6.0
Singularity Version : 0.20 
OS : Ubuntu 14

We are seeing a small number of slaves that go into a state where they are reported as active but are not picking up tasks. Going into the Mesos GUI on the slave port shows that singularity is in the 'completed frameworks' stage and there is no currently active frameworks.

The steps to reproduce this is to get a host decommissioned, wait a few minutes then have it re-activated. The host stays in an 'ACTIVE' state but does not seem to be offering any resources or picking up any tasks. 

The Mesos logs on the slave show 

```
I1022 20:25:16.269862  7656 slave.cpp:6532] Cleaning up framework Singularity
I1022 20:25:16.269906  7659 task_status_update_manager.cpp:289] Closing task status update streams for framework Singularity
I1022 20:25:16.269922  7659 gc.cpp:90] Scheduling '/mnt/mesos-slave/slaves/588ac5ce-7184-4125-8498-88a940f12565-S7/frameworks/Singularity' for gc 6.99999687618074days in the future
I1022 20:25:16.269935  7659 gc.cpp:90] Scheduling '/mnt/mesos-slave/meta/slaves/588ac5ce-7184-4125-8498-88a940f12565-S7/frameworks/Singularity' for gc 6.99999687602963days in the future
```

Restarting the mesos agent process on the host does not resolve this.

There are currently 2 ways in which we have tried to get the host running again:

1. Restarting the singularity master.
2. Stop the mesos agent. Delete the zookeeper node which corresponds to the Mesos slave agent. Start the Mesos agent.

Sometimes the above would work and sometimes not.

What would cause the slave to go into such a state ? Any suggestions on how we can restore the state to be usable again ?

**Comment by jay-chin** [comment]
So it looks like I'm able to reproduce this issue easily. This happens after a host gets decommissioned and re-activated. The host stays in an 'ACTIVE' state but does not seem to be offering any resources or picking up any tasks.

**Comment by jay-chin** [comment]
Yes this is decommissioning via SIngularity. I've not seen any timeouts or disconnections in both the Mesos or SIngularity logs. The slaves are visible in the Mesos and SIngularity GUIs. However, the mesos web ui page for the agent does not have Singularity in its running framework.

Here are the flags we use on the master:
```
--port=5050 
--log_dir=/var/log/mesos 
--cluster=qa-sf 
---logging_level=INFO 
--offer_timeout=180secs 
--quorum=2 
--work_dir=/mnt/mesos-master
```

Slave:

```
--containerizers=docker,mesos 
--docker_stop_timeout=10secs 
--docker_store_dir=/mnt/mesos-slave/docker-store 
--executor_registration_timeout=10mins 
--executor_shutdown_grace_period=1mins 
--fetcher_cache_dir=/mnt/mesos-slave/fetcher-cache 
--gc_disk_headroom=.26  
--image_providers=docker 
--ip=10.21.9.169 
--isolation=filesystem/linux,cgroups/cpu,cgroups/mem,namespaces/pid,docker/runtime,docker/volume 
--resources=cpus:32 
--work_dir=/mnt/mesos-slave 
--attributes=rackid:FIXME
```

**Comment by ssalinas** [comment]
Hmm, this is a puzzling one. I certainly don't see anything too odd about those settings for master/slave, and Singularity's decommission process doesn't actually interact directly with the slave at all. For more detail there, it's just an indicator in Singularity's internal state that it should move long running tasks off the host and not schedule new tasks on the host (all offers are immediately declined). But those interactions follow the same code paths that launching/killing a task normally would.

Do you know if Singularity is still receiving offers from this slave at all? I'm not sure what else would cause it to go into completed state without starting to dig through the mesos code. The only references I can find say that you have to explicitly tear down the framework with the master for that to happen

**Comment by jay-chin** [comment]
Is there a specific way to check that singularity is receiving offers for the slave ? Would this show in the singularity logs ?

Just to clarify, would Singularity go into a 'completed framework' state on a slave it it has no tasks running on it ? i.e. an idle slave.

**Comment by mikebell90** [comment]
@ssalinas this can be closed. It was solved way back when.
