### ISSUE TITLE
Back pressure exceptions 

### ISSUE THREAD

**Issue by mikebell90** [HubSpot/Singularity#1890]
Singularity.20

I can post some of them latter but it looks like you tackles a lot of these in.22?

Any idea of a release date for that?

**Comment by ssalinas** [comment]
I was going to attempt to push 22 the second week of january

**Comment by hari95kishore** [comment]
@ssalinas  FYI...here is the full error stack trace we have been seeing recently that @mikebell90 was referring to.



ERROR [2018-12-25 11:06:16,002] com.hubspot.singularity.mesos.SingularityMesosSchedulerClient: Observable was unexpectedly closed
! rx.exceptions.MissingBackpressureException: null
! at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.onNext(OperatorObserveOn.java:162)
! at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53)
! at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
! at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
! at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onNext(SubjectSubscriptionManager.java:225)
! at rx.subjects.PublishSubject.onNext(PublishSubject.java:113)
! at rx.observers.SerializedObserver.onNext(SerializedObserver.java:92)
! at rx.subjects.SerializedSubject.onNext(SerializedSubject.java:67)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerClient.sendCall(SingularityMesosSchedulerClient.java:261)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerClient.sendCall(SingularityMesosSchedulerClient.java:266)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerClient.decline(SingularityMesosSchedulerClient.java:307)
! at com.hubspot.singularity.mesos.SingularityNoOfferCache.cacheOffer(SingularityNoOfferCache.java:25)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl.lambda$null$5(SingularityMesosSchedulerImpl.java:241)
! at java.util.ArrayList.forEach(ArrayList.java:1257)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl.lambda$resourceOffers$8(SingularityMesosSchedulerImpl.java:237)
! at com.hubspot.singularity.mesos.SingularitySchedulerLock.runWithOffersLock(SingularitySchedulerLock.java:76)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl.callWithOffersLock(SingularityMesosSchedulerImpl.java:397)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl.resourceOffers(SingularityMesosSchedulerImpl.java:163)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl$$EnhancerByGuice$$65c75a08.CGLIB$resourceOffers$7(<generated>)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl$$EnhancerByGuice$$65c75a08$$FastClassByGuice$$9b949b80.invoke(<generated>)
! at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
! at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
! at com.palominolabs.metrics.guice.TimedInterceptor.invoke(TimedInterceptor.java:26)
! at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:77)
! at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:55)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl$$EnhancerByGuice$$65c75a08.resourceOffers(<generated>)
! at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
! at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
! at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
! at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
! at rx.internal.operators.OnSubscribeRefCount$2.onNext(OnSubscribeRefCount.java:120)
! at rx.internal.operators.OperatorPublish$PublishSubscriber.dispatch(OperatorPublish.java:588)
! at rx.internal.operators.OperatorPublish$PublishSubscriber.onNext(OperatorPublish.java:286)
! at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
! at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:399)
! at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:357)
! at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:852)
! at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.slowpath(OnSubscribeFromIterable.java:117)
! at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:89)
! at rx.Subscriber.setProducer(Subscriber.java:211)
! at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:63)
! at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:34)
! at rx.Observable.unsafeSubscribe(Observable.java:9861)
! at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:250)
! at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:147)
! at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
! at rx.observers.SerializedObserver.onNext(SerializedObserver.java:92)
! at rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:94)
! at rx.internal.operators.OperatorBufferWithTime$ExactSubscriber.emit(OperatorBufferWithTime.java:298)
! at rx.internal.operators.OperatorBufferWithTime$ExactSubscriber$1.call(OperatorBufferWithTime.java:284)
! at rx.Scheduler$Worker$1.call(Scheduler.java:136)
! at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189)
! at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
! at java.util.concurrent.FutureTask.run(FutureTask.java:266)
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
! at java.lang.Thread.run(Thread.java:748)
INFO  [2018-12-25 11:06:16,002] com.hubspot.singularity.mesos.SingularitySchedulerLock: errorConnectException - Locking state lock
INFO  [2018-12-25 11:06:16,002] com.hubspot.singularity.mesos.SingularitySchedulerLock: errorConnectException - Acquired state lock (00:00.000)
ERROR [2018-12-25 11:06:16,002] com.hubspot.singularity.mesos.SingularityMesosScheduler: Unable to connect to mesos master null
! rx.exceptions.MissingBackpressureException: null
! at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.onNext(OperatorObserveOn.java:162)
! at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53)
! at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
! at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
! at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onNext(SubjectSubscriptionManager.java:225)
! at rx.subjects.PublishSubject.onNext(PublishSubject.java:113)
! at rx.observers.SerializedObserver.onNext(SerializedObserver.java:92)
! at rx.subjects.SerializedSubject.onNext(SerializedSubject.java:67)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerClient.sendCall(SingularityMesosSchedulerClient.java:261)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerClient.sendCall(SingularityMesosSchedulerClient.java:266)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerClient.decline(SingularityMesosSchedulerClient.java:307)
! at com.hubspot.singularity.mesos.SingularityNoOfferCache.cacheOffer(SingularityNoOfferCache.java:25)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl.lambda$null$5(SingularityMesosSchedulerImpl.java:241)
! at java.util.ArrayList.forEach(ArrayList.java:1257)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl.lambda$resourceOffers$8(SingularityMesosSchedulerImpl.java:237)
! at com.hubspot.singularity.mesos.SingularitySchedulerLock.runWithOffersLock(SingularitySchedulerLock.java:76)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl.callWithOffersLock(SingularityMesosSchedulerImpl.java:397)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl.resourceOffers(SingularityMesosSchedulerImpl.java:163)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl$$EnhancerByGuice$$65c75a08.CGLIB$resourceOffers$7(<generated>)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl$$EnhancerByGuice$$65c75a08$$FastClassByGuice$$9b949b80.invoke(<generated>)
! at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
! at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
! at com.palominolabs.metrics.guice.TimedInterceptor.invoke(TimedInterceptor.java:26)
! at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:77)
! at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:55)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl$$EnhancerByGuice$$65c75a08.resourceOffers(<generated>)
! at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
! at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
! at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
! at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
! at rx.internal.operators.OnSubscribeRefCount$2.onNext(OnSubscribeRefCount.java:120)
! at rx.internal.operators.OperatorPublish$PublishSubscriber.dispatch(OperatorPublish.java:588)
! at rx.internal.operators.OperatorPublish$PublishSubscriber.onNext(OperatorPublish.java:286)
! at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
! at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:399)
! at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:357)
! at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:852)
! at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.slowpath(OnSubscribeFromIterable.java:117)
! at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:89)
! at rx.Subscriber.setProducer(Subscriber.java:211)
! at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:63)
! at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:34)
! at rx.Observable.unsafeSubscribe(Observable.java:9861)
! at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:250)
! at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:147)
! at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
! at rx.observers.SerializedObserver.onNext(SerializedObserver.java:92)
! at rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:94)
! at rx.internal.operators.OperatorBufferWithTime$ExactSubscriber.emit(OperatorBufferWithTime.java:298)
! at rx.internal.operators.OperatorBufferWithTime$ExactSubscriber$1.call(OperatorBufferWithTime.java:284)
! at rx.Scheduler$Worker$1.call(Scheduler.java:136)
! at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189)
! at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
! at java.util.concurrent.FutureTask.run(FutureTask.java:266)
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
! at java.lang.Thread.run(Thread.java:748)

**Comment by mikebell90** [comment]
Because Jay opened a separate ticket, I'll close this one.
