### ISSUE TITLE
basic auth

### ISSUE THREAD

**Issue by tpetr** [HubSpot/Singularity#19]

**Comment by ssalinas** [comment]
#1635 provides a good step towards this. Now that we are using a dropwizard authenticator that can handle multiple methods of authentication and user-lookup as well as updates to the ui to send auth headers, we could more easily add basic auth and store some basic user data in Singularity. It would just need some additional api endpoints + ui for user creation/update actions. This would also more easily enable users to take advantage of the authorization already built in to request groups

related -> https://github.com/HubSpot/Singularity/issues/1638

**Comment by tpetr** [comment]
The future is now
