### ISSUE TITLE
Constant singularity restarts with MissingBackpressureException

### ISSUE THREAD

**Issue by jay-chin** [HubSpot/Singularity#1900]
We are seeing frequent (about every 30 minutes) restarts of the singularity master with the exceptions below. We have tried tweaking rxEventBufferSize to 15000 and this has prolonged the interval between restarts (about 90 minutes).

Any ideas on what is causing this and is there anything else we can do ?

Thanks,

Jay

`
DEBUG [2019-01-10 01:34:22,110] com.hubspot.singularity.mesos.SingularitySchedulerLock: SingularityMesosSchedulerImpl$$En
hancerByGuice$$7bc5ee06#resourceOffers - Unlocking offers lock (00:00.033)
ERROR [2019-01-10 01:34:22,114] com.hubspot.singularity.mesos.SingularityMesosSchedulerClient: Observable was unexpectedl
y closed
! rx.exceptions.MissingBackpressureException: null
! at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.onNext(OperatorObserveOn.java:162)
! at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53)
! at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
! at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
! at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onNext(SubjectSubscriptionManager.java:225)
! at rx.subjects.PublishSubject.onNext(PublishSubject.java:113)
! at rx.observers.SerializedObserver.onNext(SerializedObserver.java:92)
! at rx.subjects.SerializedSubject.onNext(SerializedSubject.java:67)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerClient.sendCall(SingularityMesosSchedulerClient.java:261)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerClient.sendCall(SingularityMesosSchedulerClient.java:266)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerClient.decline(SingularityMesosSchedulerClient.java:307)
! at com.hubspot.singularity.mesos.SingularityNoOfferCache.cacheOffer(SingularityNoOfferCache.java:25)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl.lambda$null$5(SingularityMesosSchedulerImpl.java:241)
! at java.util.ArrayList.forEach(ArrayList.java:1257)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl.lambda$resourceOffers$8(SingularityMesosSchedulerImpl.java:237)
! at com.hubspot.singularity.mesos.SingularitySchedulerLock.runWithOffersLock(SingularitySchedulerLock.java:76)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl.callWithOffersLock(SingularityMesosSchedulerImpl.java:397)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl.resourceOffers(SingularityMesosSchedulerImpl.java:163)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl$$EnhancerByGuice$$7bc5ee06.CGLIB$resourceOffers$7(<generated>)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl$$EnhancerByGuice$$7bc5ee06$$FastClassByGuice$$4fe7e49c.invoke(<generated>)
! at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
! at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
! at com.palominolabs.metrics.guice.TimedInterceptor.invoke(TimedInterceptor.java:26)
! at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:77)
! at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:55)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl$$EnhancerByGuice$$7bc5ee06.resourceOffers(<generated>)
! at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
! at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
! at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
! at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
! at rx.internal.operators.OnSubscribeRefCount$2.onNext(OnSubscribeRefCount.java:120)
! at rx.internal.operators.OperatorPublish$PublishSubscriber.dispatch(OperatorPublish.java:588)
! at rx.internal.operators.OperatorPublish$PublishSubscriber.onNext(OperatorPublish.java:286)
! at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
! at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:399)
! at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:357)
! at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:852)
! at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.slowpath(OnSubscribeFromIterable.java:117)
! at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:89)
! at rx.Subscriber.setProducer(Subscriber.java:211)
! at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:63)
! at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:34)
! at rx.Observable.unsafeSubscribe(Observable.java:9861)
! at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:250)
! at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:147)
! at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
! at rx.observers.SerializedObserver.onNext(SerializedObserver.java:92)
! at rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:94)
! at rx.internal.operators.OperatorBufferWithTime$ExactSubscriber.emit(OperatorBufferWithTime.java:298)
! at rx.internal.operators.OperatorBufferWithTime$ExactSubscriber$1.call(OperatorBufferWithTime.java:284)
! at rx.Scheduler$Worker$1.call(Scheduler.java:136)
! at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189)
! at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
! at java.util.concurrent.FutureTask.run(FutureTask.java:266)
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
! at java.lang.Thread.run(Thread.java:748)
INFO  [2019-01-10 01:34:22,115] com.hubspot.singularity.mesos.SingularitySchedulerLock: errorConnectException - Locking state lock
INFO  [2019-01-10 01:34:22,115] com.hubspot.singularity.mesos.SingularitySchedulerLock: errorConnectException - Acquired state lock (00:00.000)
ERROR [2019-01-10 01:34:22,115] com.hubspot.singularity.mesos.SingularityMesosScheduler: Unable to connect to mesos master null
! rx.exceptions.MissingBackpressureException: null
`

**Comment by ssalinas** [comment]
What version are you running? We just released 0.22 with a bunch of backpressure updates

**Comment by jay-chin** [comment]
we are running 0.20.1

**Comment by jay-chin** [comment]
Thanks. We will try upgrading to 0.22.

**Comment by ssalinas** [comment]
Going to close this since there are a bunch of updates for this in 0.22. If you find you are still hitting the issue, feel free to reopen
