### ISSUE TITLE
where can I get an rpm for centos7?

### ISSUE THREAD

**Issue by f1-outsourcing** [HubSpot/Singularity#2084]
where can I get an rpm for centos7?

**Comment by ssalinas** [comment]
I think you filed this on the wrong repo? We don't ship Singularity as an rpm

**Comment by f1-outsourcing** [comment]
No, I assumed that you have ready packages (like marathon, aurora) for the most generic distributions.

**Comment by ssalinas** [comment]
We do not currently ship an rpm and don't have a plan to right now. At the moment the easiest way to get at Singularity is the jars in maven

https://getsingularity.com/Docs/getting-started/install.html
