### ISSUE TITLE
Auth issues in Singularity 1.3.0

### ISSUE THREAD

**Issue by yuriy-filatov** [HubSpot/Singularity#2145]
Hey, @ssalinas 
Here's a report for 1.3.0 build.
~~Our env: cluster of four 1.2.0 + one 1.3.0, leader is 1.2.0.~~

~~RO user (requiredGroups + globalReadOnlyGroups)~~
- ~~able to deploy/edit/pause/unpause/remove requests, everything actually (shouldn't be)~~
- ~~able to delete racks (shouldn't be)~~
- ~~unable to manage active agents: freeze/decomission throw 405 and flag as inactive -- 403 (seems OK but different codes)~~
- ~~able to delete inactive agents (shouldn't be)~~
- utilization is rendering, but broken (access to /usage/agents is not available)
looks OK

~~Jita user (requiredGroups+jitaGroups):~~
- ~~able to deploy/edit/pause/unpause/remove requests, everything actually (looks OK for jita)~~
- ~~able to delete racks (shouldn't be)~~
- ~~unable to manage active agents: freeze/decomission throw 405 and flag as inactive -- 403 (seems OK but different codes)~~
- ~~able to delete inactive agents (shouldn't be)~~
- utilization is rendering, but broken (access to /usage/agents is not available)
looks OK

~~Admin user (requiredGroups+adminGroup):~~

- ~~admin -> agents -> freeze/decomission: 405 method not allowed (should be able; might this be related to a bunch of recent renames?)~~
- utilization is not rendering at all
rest looks OK

Any mail-reported actions (pause/unpause for example) don't have singularityUserId (actually this is a long-runner, unrelated to current issue and is observed at least for last 12 months). Can singularityUserId be also parsed from http://URI/singularity/api/auth/user from user:id field if auth is enabled?

**Comment by ssalinas** [comment]
Hey, first comment is that Singularity wasn't generally set up to run mixed versions like that. For example the UI moved to the new naming, so if you got the UI from 1.3 but then hit a 1.2 instance it wouldn't work in all cases. Upgrading all should account for any of the 405s

utilization is a known issue

Can look closer at some of the other descriptions in a bit

**Comment by yuriy-filatov** [comment]
Fixed my comment above, thanks.

**Comment by yuriy-filatov** [comment]
Thanks for the update, we've rebuilt our conf according to new docs and rechecked everything -- looks very nice, thank you!

Only annoying thing is that we're not getting userId in email logback, even for authorized user:
![logback](https://user-images.githubusercontent.com/6918427/94947671-b4f6e280-04e6-11eb-985b-cc3b8dd8d77e.JPG)

**Comment by ssalinas** [comment]
Interesting, not the same on our side of things. Would have to look into that one more. When you look on the request history section in the UI, does it show the user there, or is it missing in that context as well?

**Comment by yuriy-filatov** [comment]
Nope, everything is blank.
Even on initial deploy we don't receive username.
Deploy goes through something like
`curl -X POST http://uri/singularity/api/requests -d "$(cat test.json )" -H 'Cookie: s9yauth=some_base64' -H 'Content-Type: application/json' | jq

**Comment by yuriy-filatov** [comment]
We've checked available versions of Singularity -- 0.17.1 is the last version to ask for username on initial connection and save into localStorage. 

Enforcing `%s/api/deploys?user=${user}` during deployment gives required result during deploy, but any other actions have blank username.

**Comment by ssalinas** [comment]
It should be getting the username from the webhook payload for auth. I can check if it's pulling the right field or possibly not falling back to the email/id or something.

**Comment by yuriy-filatov** [comment]
We have something like 
`{
  "user": {
    "id": "s9y_admin",
    "name": "s9y admin",
    "email": "",
    "groups": [
      "s9y-admin-group"
    ],
    "scopes": [
      "s9y-admin-group"
    ],
    "authenticated": true
  },
  "error": ""
}`
after auth.
Should we provide email as well?

**Comment by ssalinas** [comment]
Could do that in short term and it may fix it, didn't get a chance to look at the code yet. I thought it was email, with a fall back to name/id, but maybe not

**Comment by yuriy-filatov** [comment]
Hey @ssalinas 
Hope my message finds you well.
Any chances this issue can be resolved?

**Comment by yuriy-filatov** [comment]
Hey @ssalinas 
Any chances this can be resolved?

**Comment by yuriy-filatov** [comment]
Thanks @ssalinas , we'll take a look into falling back to user email.
