### ISSUE TITLE
GRPC healthchecks in Singularity

### ISSUE THREAD

**Issue by yuriy-filatov** [HubSpot/Singularity#2149]
Hey there.
We're currently struggling with singularity healthchecks for grpc-enabled service.
Service is exposed via Baragon agent on haproxy and requires proper backend scaling.
Initially there's some launch timeout for our service, but Singularity marks it as immediately available (as we can't provide usual HC here) and upserts proper route into Baragon/Haproxy. Main problem here that backend is not really available and Haproxy treats it as dead --> scaling is not working as we want it to. 
Will it be possible to add some sort of grpc HC into Singularity to work out of the box?

**Comment by ssalinas** [comment]
I believe @baconmania implemented this a while back. There is a `HTTP2` option in the healthcheck protocol [here](https://github.com/HubSpot/Singularity/blob/4f7a41d72617b333c06fd96cc473c8db0faf6f7a/SingularityBase/src/main/java/com/hubspot/deploy/HealthcheckOptions.java#L128-L133). Not been well utilized on our side though, so if it's got issues let us know

**Comment by yuriy-filatov** [comment]
Thanks Stephen, will give it a try.

**Comment by yuriy-filatov** [comment]
Looks like that's not our saver. We need grpc-based check in order to make things work without any additional proxies.

**Comment by yuriy-filatov** [comment]
We've decided to proceed with http-enabled side container which is checking deployment health and reports into s9y, works fine for our needs.
