### ISSUE TITLE
More flexibility in task placement / scheduling.

### ISSUE THREAD

**Issue by tpetr** [HubSpot/Singularity#218]
We need to put more thought into task placement / scheduling beyond HubSpot's environment. For example, there's a need to support the situation where a user wants to pack multiple tasks from the same deploy onto the same slave.

We should also take a look at how Marathon does this -- I remember them having something almost like a query language for this? Not that we necessarily need to go that in-depth.

/cc @hgschmie @wsorenson

**Comment by stevenschlansker** [comment]
Should this issue be closed now?  Seemingly a lot of it has been merged in for a while, and any followup might be better filed as separate issues?

**Comment by jloisel** [comment]
Can be closed for me.
