### ISSUE TITLE
PriorityFreeze in Singularity deploy/request

### ISSUE THREAD

**Issue by yuriy-filatov** [HubSpot/Singularity#2294]
Hey
We're currently looking into adding priorotyFreeze into our pipeline, but struggle to find the proper key and wrapping for our request.
Can you please share the knowledge -- how to add the priority level to the deployment yaml?
Thanks.

**Comment by ssalinas** [comment]
priority is a request level setting. `taskPriorityLevel` field on the request json (not deploy json). Then in Singulairty UI you can freeze launches of all tasks below priority level X if you need to. It also influences scheduling order with higher priorities coming first
