### ISSUE TITLE
Notification on deploy failed/rolled back

### ISSUE THREAD

**Issue by yuriy-filatov** [HubSpot/Singularity#2308]
Hey @ssalinas 
We've faced a few issues with 'lost' deployment.
We have a CD in place which is deploying yamls into S9y. For numerous reasons the deploy at this stage might be green, but the deploy in S9y might be failed and automatically rolled back -- can this action trigger the notification?

At the moment S9y deployment can create a task, fail and rollback silently.
Deploy status will change to 'Failed' in the UI (also, silently).

**Comment by ssalinas** [comment]
Hey @yuriy-filatov , we aren't making additional changes to the open source version of Singularity at this point. Internally what we do for this case is poll for the status of the deploy on the singularity api to determine if it failed or succeeded.

**Comment by yuriy-filatov** [comment]
I see, thanks! We probably will add extra check to the deployer.
