### ISSUE TITLE
make sure that jade4j works with java 8

### ISSUE THREAD

**Issue by hgschmie** [HubSpot/Singularity#245]
@stevenschlansker: java4j depends on asm 3.3.1 which may not be java 8 compatible.

**Comment by ssalinas** [comment]
Hey folks, been a while since we revisited this. Are there currently still any users that would have an issue with us moving to java 8?

**Comment by stevenschlansker** [comment]
We'd support that!

**Comment by ssalinas** [comment]
JAVA8 PR is open and working well, jade4j no longer an issue so closing this guy
