### ISSUE TITLE
Singularity should be able to handle registration, re-registration, and leadership changes without aborting

### ISSUE THREAD

**Issue by wsorenson** [HubSpot/Singularity#273]

**Comment by tpetr** [comment]
@wsorenson thoughts on tackling this? or are we happy with our abort strategy?

**Comment by stevenschlansker** [comment]
End-user opinion: the aborts are worrying but once you learn to stop fretting they really do not present any sort of urgent problem to us.

**Comment by ssalinas** [comment]
fixed in https://github.com/HubSpot/Singularity/pull/2032
