### ISSUE TITLE
Request create: default 'Load Balanced' on only if Baragon is correctly configured

### ISSUE THREAD

**Issue by stevenschlansker** [HubSpot/Singularity#285]
As reported by @eliast in #277, the default configuration of Singularity does not require Baragon but enables 'load balanced' by default, which is guaranteed to fail.

I've filed #284 to make the default off, but I think it would be even better if the default is on only if Baragon is configured.  I'm not much of a UI whiz so I did the easy thing and am filing this as a followup.

**Comment by ssalinas** [comment]
This was added in #811
