### ISSUE TITLE
Can't find installation instructions on non-Vagrant machines

### ISSUE THREAD

**Issue by igormoochnick** [HubSpot/Singularity#349]
Is there an instruction page to install Singularity from a package?
What are the required config files and command line parameters?

 Thanks

**Comment by ZiaBhatti** [comment]
I am looking at the exact same issue and the same provision script.

**Comment by tpetr** [comment]
Hey folks, i moved the vagrant information into [vagrant.md](https://github.com/HubSpot/Singularity/blob/master/Docs/vagrant.md) and have updated [install.md](https://github.com/HubSpot/Singularity/blob/master/Docs/install.md) to describe how to install Singularity for non-vagrant machines. Let me know if anything in it is unclear.
