### ISSUE TITLE
SingularityExecutor default configuration actually does not work

### ISSUE THREAD

**Issue by hgschmie** [HubSpot/Singularity#352]
The config defaults setting is missing the following properties:

(From SingularityExecutorConfigurationLoader)

* executor.default.user
* executor.global.task.definition.directory
* executor.s3.uploader.bucket
* executor.s3.uploader.pattern

(From SingularityRunnerBaseConfigurationLoader)

* root.log.directory

If these are mandatory (and need to be loaded from the configuration files), then the Executor should crash with a more meaningful error message than a bunch of Guice "could not find binding" errors.

**Comment by ssalinas** [comment]
The singularity executor and other runnables now will throw more descriptive errors. For example:

```
ConfigurationValidationException: /etc/singularity.executor.yaml has an error:
  * defaultRunAsUser may not be empty (was null)
```
