### ISSUE TITLE
Processing of extra command line arguments with docker containers

### ISSUE THREAD

**Issue by martinstuder** [HubSpot/Singularity#376]
Extra command line arguments in a request to a docker container do not seem to be supported with the current implementation of the SingularityMesosTaskBuilder.

Assume the following the definition of a deployment:
```
{
  "deploy": {
        "requestId": "myrequest",
        "id": "12",
        "command": "r",
        "containerInfo": {
            "type": "DOCKER",
            "docker": {
                "image": "rocker/r-base",
                "portMappings": []
            }
        },
        "resources": {
            "cpus": 0.1,
            "memoryMb": 128,
            "numPorts": 0
        }
    }
}
```

For completeness here is the definition of the associated (on-demand) request:
```
{
    "request": {
        "id": "myrequest",
        "owners": [
            "me@gmail.com"
        ],
        "daemon": false
    },
    "state": "ACTIVE",
    "requestDeployState": {
        "requestId": "myrequest",
        "activeDeploy": {
            "requestId": "myrequest",
            "deployId": "12",
            "timestamp": 1419880060919
        }
    },
    "instances": 1,
    "hasMoreThanOneInstance": false,
    "canBeScaled": false
}
```

When POSTing `-e "print('hello world')"` to http://hostname:7099/singularity/api/requests/request/myrequest/run I would expect the following command to be run on the above specified docker container: `r -e "print('hello world')"`

This seems to be pretty close according to the `/var/log/mesos/mesos-slave.INFO` log file:
```
E1229 20:16:54.056499  3232 slave.cpp:2787] Container 'a286e452-2afe-4410-9785-ea15b8bbcbbd' for executor 'myrequest-12-1419880613593-1-falcon-DEFAULT' of framework 'Singularity' failed to start: Failed to 'docker run -d -c 102 -m 134217728 -e INSTANCE_NO=1 -e TASK_HOST=falcon -e TASK_REQUEST_ID=myrequest -e TASK_DEPLOY_ID=12 -e ESTIMATED_INSTANCE_COUNT=1 -e MESOS_SANDBOX=/mnt/mesos/sandbox -v /tmp/mesos/slaves/20141229-201537-16842879-5050-3183-S0/frameworks/Singularity/executors/myrequest-12-1419880613593-1-falcon-DEFAULT/runs/a286e452-2afe-4410-9785-ea15b8bbcbbd:/mnt/mesos/sandbox --net host --name mesos-a286e452-2afe-4410-9785-ea15b8bbcbbd rocker/r-base r -e "print('hello world')"': exit status = exited with status 1 stderr = 2014/12/29 20:16:54 Error response from daemon: Cannot start container 3ec96d9866a86bb337f142560fb92fbd47e0f7a8799e7907965df2940141b0a2: exec: "r -e \"print('hello world')\"": executable file not found in $PATH
```

The problem, however, is, that with the call to docker, docker seems to be believe that `r -e "print('hello world')"` is a single executable. There might be two issues here:

1) "maybeCmdLineArgs" for a [SingularityPendingTask](https://github.com/HubSpot/Singularity/blob/e4248134a4eff89ee489c113ef066b44f9063cb3/SingularityBase/src/main/java/com/hubspot/singularity/SingularityPendingTask.java#L13) is a single String rather than e.g. a List<String> like the field 'extraCmdLineArgs' in  [ExecutorData](https://github.com/HubSpot/Singularity/blob/8a9ccfc259e87d7857665020b0eccb193be58b7b/SingularityBase/src/main/java/com/hubspot/deploy/ExecutorData.java#L22)

2) The processing of the command and the 'maybeCmdLineArgs' in the [SingularityMesosTaskBuilder](https://github.com/HubSpot/Singularity/blob/master/SingularityService/src/main/java/com/hubspot/singularity/mesos/SingularityMesosTaskBuilder.java#L258) builds a compound command leading to the behavior shown above (see also the processing of the CommandInfo on the [mesos side](https://github.com/apache/mesos/blob/master/src/docker/docker.cpp#L452)). Rather, it seems like the 'maybeCmdLineArgs' should be processed similar to the deploy arguments as seen [here](https://github.com/HubSpot/Singularity/blob/master/SingularityService/src/main/java/com/hubspot/singularity/mesos/SingularityMesosTaskBuilder.java#L273)

See also the following post on [Google Groups](https://groups.google.com/forum/#!topic/singularity-users/nu_fOwC-XyE).

**Comment by wsorenson** [comment]
Great. Should be easy to make the API / taskBuilder change. We can open another issue for processing the field in the UI.

**Comment by wsorenson** [comment]
Just looking at this and not yet sure the best way to change all of our JSON models to maximize compatibility.

**Comment by wsorenson** [comment]
See #415
