### ISSUE TITLE
UI file browser should show images properly

### ISSUE THREAD

**Issue by jaredstehler** [HubSpot/Singularity#390]
When I click on a PNG file in the file browser, it opens as a text document, rather than something more graphical.

![screen shot 2015-01-11 at 9 55 42 pm](https://cloud.githubusercontent.com/assets/2022218/5698480/c781e27c-99dc-11e4-81bc-a764dee72537.png)

**Comment by ssalinas** [comment]
Given the structure of the new tailer, this is likely not something we are going to support. The current tailer will not allow you to click on files it cannot view (based on extension). We can certainly take a crack at #1357 at some point so that downloading the files works more smoothly.
