### ISSUE TITLE
Consider consolidating the two sets of Baragon Provisioner scripts

### ISSUE THREAD

**Issue by eherot** [HubSpot/Singularity#393]
There are some here: https://github.com/HubSpot/Baragon/blob/master/vagrant/
And a completely different set here: https://github.com/HubSpot/Singularity/tree/master/vagrant

They seem to do basically the same thing but are in a slightly different state of maintenance.

**Comment by tpetr** [comment]
i think we'll do one better and use the baragon chef cookbook

**Comment by eherot** [comment]
Haha awesome. In that case can you make double sure that the version of the template I put in that cookbook is actually correct?

**Comment by ssalinas** [comment]
New docker-based workflow just downloads images for Baragon, no provisioning needed :) , closing this
