### ISSUE TITLE
do a better job surfacing SingularityDeployResult in the UI

### ISSUE THREAD

**Issue by tpetr** [HubSpot/Singularity#460]
The message field of `SingularityDeployResult` contains useful information for diagnosing a failed deploy, we need to do a better job surfacing it in the UI. This could be as simple as including the message field in the Deploy History table on the request page.

/cc @eherot

**Comment by eherot** [comment]
:+1: 

Not just "useful" but also the *only* way to tell if you've asked for resources you don't have (which I suspect devs will do a lot in our relatively small cluster.

**Comment by tpetr** [comment]
#629 should solve this once and for all
