### ISSUE TITLE
investigate a new request type for running a task on every slave

### ISSUE THREAD

**Issue by tpetr** [HubSpot/Singularity#469]
I think this fills an important use case, but we need to figure out:
- how to best prioritize resource allocation between the different request types
- how to best visualize this type of request, especially since it could have a large # of tasks associated with it

/cc @stevenschlansker

**Comment by stevenschlansker** [comment]
Thanks!

**Comment by apognu** [comment]
I would be very interested in that feature, if it's still on the roadmap.

**Comment by bradjorgensen** [comment]
+1

**Comment by ozayduman** [comment]
+1

**Comment by stevenschlansker** [comment]
Is this fixed by #1519 ?

**Comment by ssalinas** [comment]
correct, see a bit more in [this comment](https://github.com/HubSpot/Singularity/pull/1519#issue-225079969) or the docs as to how to use it
