### ISSUE TITLE
Request deletion fails

### ISSUE THREAD

**Issue by jloisel** [HubSpot/Singularity#478]
We have an issue with Singularity 0.4.1, you can reproduce by doing:
- create a request,
- create a deploy inside this request,
- remove request,
- re-create request: it fails saying the request already exists.

Even when deleting /singularity zkNode, flushing Mysql database and restarting Singularity, data remains. Where is the data stored ? How can i "really" delete a request ?

**Comment by wsorenson** [comment]
I think there might be two things going on here:

1) If you try to re-create it while it is being cleaned up it will fail. There is a queue which processes removal of requests. Once it has been drained you should be able to re-create the request.

2) You should be able to trivially purge the data - most operational data is in ZooKeeper.

**Comment by jloisel** [comment]
I'm going to make sure having stopped Singularity before doing an "rmr  /singularity" on zookeeper, to make sure there is nothing left.
