### ISSUE TITLE
SingularityUI cuts off names of S3 logs in unfortunate ways

### ISSUE THREAD

**Issue by wolfd** [HubSpot/Singularity#486]
![image](https://cloud.githubusercontent.com/assets/930169/6761755/a9a2bf94-cf2c-11e4-8600-5146dadc20a6.png)

A better solution might be to cut out the middle/beginning of the filename instead of the end.

**Comment by tpetr** [comment]
fixed in https://github.com/HubSpot/Singularity/pull/635, when `taskS3LogOmitPrefix` is set appropriately
