### ISSUE TITLE
Administrator should be able to clear 'cooldown' request state

### ISSUE THREAD

**Issue by stevenschlansker** [HubSpot/Singularity#524]
Often cooldown happens because of an administrative error.  Perhaps a required database is down, or there was a temporary DNS outage.

Once the administrator believes she has cleared the outage, it is frustrating to watch Singularity cool your (hypothetically now working) task off.  Especially if you are getting phone calls from frustrated end users.

A button to reset the cooldown state (or at least override it once, making the delayed tasks launch immediately) would be very helpful.

**Comment by tpetr** [comment]
We've been burned by this internally too -- we're going to fix it in 2 ways: a button to clear the cooldown state of the request, and fix Run Now to work on scheduled tasks (only supported for cron jobs currently)

**Comment by tpetr** [comment]
^ added `Exit Cooldown` button to Request page when request is in cooldown state, which clears the cooldown setting and immediately schedules all pending tasks

**Comment by benhardy** [comment]
Thanks @tpetr !
