### ISSUE TITLE
SingularityClient.getSingularityRequest() should return collection of SingularityRequestParent

### ISSUE THREAD

**Issue by jloisel** [HubSpot/Singularity#525]
Apparently, the Json API returns a collection of SingularityRequestParent.

Confirmed in the code in RequestResource:
https://github.com/HubSpot/Singularity/blob/e67c24d9a8c51d777922931a820b8580322b239a/SingularityService/src/main/java/com/hubspot/singularity/resources/RequestResource.java#L345

**Comment by tpetr** [comment]
fixed in https://github.com/HubSpot/Singularity/pull/554
