### ISSUE TITLE
Allow for custom load balancer options to be passed to baragon

### ISSUE THREAD

**Issue by EdHurtig** [HubSpot/Singularity#531]
Baragon exposes an `nginxExtraConfigs` option which seems to be ignored when a singularity deploy is created.  

From https://github.com/HubSpot/Baragon/blob/master/docs/baragon_api_docs.md
>```
{
  "loadBalancerRequestId":"requestId", # Unique request id
  "loadBalancerService":{
    "serviceId":"testService",
    "owners":["owner@example.com"],
    "serviceBasePath":"/basepath",
    "loadBalancerGroups":["vagrant"],
    "options":{
        "nginxExtraConfigs": [
            "rewrite ^/test(.*) /test/v1/$1 last;"
        ]
    }
  },
  "addUpstreams":[
    {"upstream":"example.com:80","requestId":"requestId","rack":"us_east_1a"}
  ],
  "removeUpstreams":[]
}
```

It would be great if we could somehow specify a hash in a Deploy that will get passed to Baragon.

**Comment by ssalinas** [comment]
@edhurtig , objects added to the loadBalancerOptions field of the [deploy](https://github.com/HubSpot/Singularity/blob/master/SingularityBase/src/main/java/com/hubspot/singularity/SingularityDeploy.java) will show up in the options hash on the Baragon request

**Comment by EdHurtig** [comment]
Thanks @ssalinas! I will check that out. Closing for now

**Comment by EdHurtig** [comment]
Worked like a charm

**Comment by ssalinas** [comment]
:smile:
