### ISSUE TITLE
Include link to task and request from within file view

### ISSUE THREAD

**Issue by mveitas** [HubSpot/Singularity#563]
When viewing a file in Singularity, it would be helpful to have a link back to the request and the current task at the top of the page.

![singularity_prod](https://cloud.githubusercontent.com/assets/439521/7935873/550fabc6-0902-11e5-8ca5-783102817ae6.png)

**Comment by benrlodge** [comment]
clicking on the root link in your screenshot will bring you back to the task page, and then from there you can click the link of its associated request at the top of the task page. Is that what you're trying to accomplish?

**Comment by mveitas** [comment]
The intent was to get back to the requests page with as few clicks as possible

**Comment by benrlodge** [comment]
got it, thanks.

**Comment by mveitas** [comment]
Looks like this is being addressed in https://github.com/HubSpot/Singularity/pull/739
