### ISSUE TITLE
Show DECOM badges on tasks based on SingularityTaskCleanup data

### ISSUE THREAD

**Issue by tpetr** [HubSpot/Singularity#583]
Currently we're showing the `DECOM` badge on tasks if their offer hostname matches a slave hostname that's in the `DECOMISSIONING` state, but that can backfire if you also have an `ACTIVE` slave with the same hostname. A more accurate way to tell if a task is running on a decommissioned slave is to check if the task has a matching SingularityTaskCleanup with cleanupType == `DECOMISSIONING`

/cc @jeffbyrnes @ssalinas

**Comment by jeffbyrnes** [comment]
Yeah, we were bit by this recently, and really were thrown until we realized it was probably just b/c the hostnames match.

**Comment by tpetr** [comment]
fixed in https://github.com/HubSpot/Singularity/pull/728
