### ISSUE TITLE
Does Singularity support docker image force pull 

### ISSUE THREAD

**Issue by sourcec0de** [HubSpot/Singularity#584]
I would like to have a deploy object contain a tag of latest, but its not pulling the latest docker image after the first pull. I know in Marathon you can specify `forcePullImage` and that gets passed to mesos. Is there a way to replicate this behavior in Singularity do we need a pull request?

**Comment by ssalinas** [comment]
I believe `forcePullImage` was added as of mesos 0.22, right now Singularity does not pass that field along, it would need to be added

**Comment by ZiaBhatti** [comment]
Certainly needed

**Comment by sourcec0de** [comment]
After carefully thinking about my deployment scheme not force pulling an image makes the most sense in a production environment. You absolutely need to be tagging the docker images and pulling specific versions otherwise a rollback scenario doesn't even work. You can't roll back to latest. `forcePullImage` makes the most sense in a development environment where you're maybe pushing a new image and you want to avoid tagging.

This feature may not be as important as I originally thought. Perhaps another layer I.E a cli tool that can generate the deploy config would be a good option and in that tool you could query a docker repo for the version you want to deploy.

**Comment by ssalinas** [comment]
+1 for not pulling latest all the time, it's always iffy to put code you may not have seen before into production (or any environment really...)

That said, feel free to leave this issue open and we can implement the feature in order to keep in line with options available in mesos. also, There are no cli tools for Singularity deploy json currently, but go ahead and PR it if you have one

**Comment by sourcec0de** [comment]
:smiling_imp: SOOONNN!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by sourcec0de** [comment]
Does anyone care what language it's in? I'll likely write it in go and have the build server git release a binary if I just have it in a separate repo.

**Comment by tpetr** [comment]
added in https://github.com/HubSpot/Singularity/pull/657
