### ISSUE TITLE
TASK_HOST environment variable uses the Slave ID instead of the actual hostname

### ISSUE THREAD

**Issue by EdHurtig** [HubSpot/Singularity#588]
Singularity provides tasks with an invalid hostname in the TASK_HOST environment variable
```
"command": {
    "environment": {
        "variables": [
            ...
            {
                "name": "TASK_HOST",
                "value": "stage_mesos_slave_1b.priv.evertrue.com"
            },
            ...
```

The actual task host has hyphens instead of underscores, a consequence of data sanitization when generating slave IDs

See: https://github.com/HubSpot/Singularity/blob/master/SingularityService/src/main/java/com/hubspot/singularity/mesos/SingularityMesosTaskBuilder.java#L174-L186

Possible Stumbling block: https://github.com/HubSpot/Singularity/blob/master/SingularityBase/src/main/java/com/hubspot/singularity/SingularityTaskId.java#L124

**Comment by wsorenson** [comment]
We set TASK_HOST in two places.

The first is fixed in https://github.com/HubSpot/Singularity/commit/3868da9189bb05e259de0d9b272d737ea797360e

The second is fixed in https://github.com/HubSpot/Singularity/pull/616

**Comment by tpetr** [comment]
This is fixed in https://github.com/HubSpot/Singularity/releases/tag/Singularity-0.4.3

**Comment by EdHurtig** [comment]
:+1: thanks!
