### ISSUE TITLE
Add support for force_pull_image

### ISSUE THREAD

**Issue by icksa** [HubSpot/Singularity#594]
Mesos 0.22 introduced a new option to DockerInfo called "force_pull_image", see:

https://issues.apache.org/jira/browse/MESOS-1886

This option causes mesos to always attempt to pull versions of an existing image. I did not see a way to leverage this option when launching docker containers with singularity...would it be possible to add support for force_pull_image?

**Comment by ssalinas** [comment]
duplicate of #584
