### ISSUE TITLE
Some requests cannot be viewed from Requests page

### ISSUE THREAD

**Issue by stevenschlansker** [HubSpot/Singularity#596]
Running 0.4.2 release:

![screen shot 2015-07-07 at 2 50 28 pm](https://cloud.githubusercontent.com/assets/129097/8558211/8ceb5f2e-24b7-11e5-8719-96433307a207.png)
![screen shot 2015-07-07 at 2 50 36 pm](https://cloud.githubusercontent.com/assets/129097/8558213/8f53fcb2-24b7-11e5-915a-dd22b5a9450d.png)

**Comment by stevenschlansker** [comment]
According to the network inspector, no 404 was ever returned:
![screen shot 2015-07-07 at 2 59 06 pm](https://cloud.githubusercontent.com/assets/129097/8558408/c85f648c-24b8-11e5-9d31-2cfd67f63381.png)

**Comment by tpetr** [comment]
@stevenschlansker yeah, sounds like an issue with the Backbone router -- are you seeing this for all Requests, or that one?

**Comment by stevenschlansker** [comment]
Some arbitrary subset.  I'd say 30%?

**Comment by tpetr** [comment]
What's the JSON value of the `/api/history/request/ct-tms-iris/requests/` response? Is it `[]` by any chance?

**Comment by stevenschlansker** [comment]
Indeed it is `[]`
