### ISSUE TITLE
Deploy history no longer shows actual deployment blob

### ISSUE THREAD

**Issue by stevenschlansker** [HubSpot/Singularity#627]
I'm pretty sure this used to work, but now when I click on the `{}` button to see the JSON for a deploy in the "Deploy history", all I see is:
```
{
    "deployResult": {
        "deployState": "SUCCEEDED",
        "timestamp": 1436377513881
    },
    "deployMarker": {
        "requestId": "teamcity-agent",
        "deployId": "ctomlinson.2015.07.08T17.43.38",
        "timestamp": 1436377417759
    }
}
```

which is not very helpful.  What was actually deployed?!

**Comment by tpetr** [comment]
`HistoryResource.getDeploys()` (i.e. `.../api/history/request/{requestId}/deploys`) needs to be documented better -- it returns a minimal view of deploys on purpose (the `SingularityDeploy` object can be rather large). Requesting a specific deploy (i.e. `.../api/history/request/{requestId}/deploy/{deployId}`) should give you the fully populated `SingularityDeployHistory` object you're expecting.

A full Deploy view is being created in #629, which should be a big improvement over the raw JSON.
