### ISSUE TITLE
Capture task placement decisions in task JSON

### ISSUE THREAD

**Issue by stevenschlansker** [HubSpot/Singularity#636]
Currently, when a task is being placed, the only debugging aid is a bunch of `LOG.trace` statements e.g.
```
LOG.trace("Rejecting OPTIMISTIC task {} from slave {} ({}) due to numOnSlave {}", taskRequest.getRequest().getId(), slaveId, host, numOnSlave);
```

This means if a task cannot be placed (possibly failing a deploy as `OVERDUE`) you have little recourse until you are willing to roll a new logging config that enables trace, retry the deploy, and then disable it when you are done.

It would be nice if decisions such as this were collected in the task JSON, similar to how the healthcheck results are, so end-users can get some self-service diagnostics (even if the UI is not very pretty at the start).

**Comment by wsorenson** [comment]
True, there are a few other cases where you must see the logs instead of interpreting API response (particularly when load balancer + deploys fail.)

**Comment by ssalinas** [comment]
After adding #893 we have more of this information. Any failed deploys will now have a failure reason enum, one of the values of which is `TASK_COULD_NOT_BE_SCHEDULED` and has a message related to the fact that there might not be enough resources. Other failure reasons are served up as well and available on the deploy page and in the deployResult json

As for the tracking of the lacking resources as they happen, that is what #898 gets at it seems, so I am going to close this issue and we can track the progress of surfacing overdue task information better in that issue
