### ISSUE TITLE
Slave list shows nonexistent slave

### ISSUE THREAD

**Issue by samsalisbury** [HubSpot/Singularity#637]
For some reason, Singularity is currently showing me a slave which does not in fact exist in the cluster [1]. It has the same hostname as another slave, but a different ID, and possibly existed in the past, but no longer. Mesos itself does not show this slave [2].

It's not a UI bug, since /api/slaves is also showing 5 active slaves, when there are in fact 4.

I have not yet determined if this is impacting task placement.

[1] _Singularity web UI slave list. The two with same hostname are circled, and the bogus slave ID is highlighted_
![screen shot 2015-07-29 at 11 07 33](https://cloud.githubusercontent.com/assets/111437/8955132/18c7aefe-35e2-11e5-8043-5b685cda28a3.png)

[2] _Mesos Web UI Slave List from the same cluster at the same time as the above singularity UI_
![screen shot 2015-07-29 at 11 09 41](https://cloud.githubusercontent.com/assets/111437/8955174/6146186e-35e2-11e5-9fc1-25214e1f03cf.png)

**Comment by wsorenson** [comment]
I wonder if Mesos never delivered the framework message about this slave. 

This the only case I can think of where it would continue to show it as active. If you restart Singularity, it should reconcile slave state with Mesos and move this slave to dead.

Alternatively, you can simply click to remove it in the UI.

Assuming there isn't a bug, which is possible, the only other action I can think of taking is to write a poller to reconcile state in the situation that Mesos does not deliver any updates about this slave.

Do you have logs from Singularity? Might be interesting to grep them for that ID.

**Comment by ssalinas** [comment]
We should probably have Singularity automatically reconcile every once in a while, or if it hasn't gotten an offer in some amount of time from a slave. That said, it *will not* impact new task placement. The task placement is done based on incoming offers. Since the slave was not active according to the master, there wouldn't be any offers coming in for it, so no new tasks would be scheduled there.

**Comment by stevenschlansker** [comment]
Can confirm, the issue looks to be largely cosmetic and doesn't affect task placement or other critical functionality.  It mostly just looks weird and sows distrust in administrators and users.
