### ISSUE TITLE
Track run request through processing

### ISSUE THREAD

**Issue by sannessa** [HubSpot/Singularity#666]
When I submit a run request via the API through /api/requests/request/{requestId}/run I don't have a way to verify the completion of that request.

I can hit /api/history/request/{requestId}/tasks/active to see active tasks and /api/history/request/{requestId}/tasks to see tasks that have finished but I cannot link a run request to a finished task.

A UID that tracks the run request throughout the entire process would solve my problem.

**Comment by wsorenson** [comment]
This is available in master now.
