### ISSUE TITLE
Can't upgrade to Elasticsearch 2.0.0: Netty version conflict with HorizonNing

### ISSUE THREAD

**Issue by jloisel** [HubSpot/Singularity#754]
We're completely stuck in our upgrade, Singularity depends on HorizonNing which uses an outdated version of Netty (3.9.2.Final), while Elasticsearch 2.0.0 uses Netty 3.10.5.Final. This causes the following issue:

> java.lang.NoSuchMethodError: org.jboss.netty.handler.codec.http.HttpRequest.setHeader(Ljava/lang/String;Ljava/lang/Object;)V
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.construct(NettyAsyncHttpProvider.java:700)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.buildRequest(NettyAsyncHttpProvider.java:655)
	at com.ning.http.client.providers.netty.NettyConnectListener$Builder.build(NettyConnectListener.java:144)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.doConnect(NettyAsyncHttpProvider.java:1069)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.execute(NettyAsyncHttpProvider.java:934)
	at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:499)
	at com.hubspot.horizon.ning.NingAsyncHttpClient$1.run(NingAsyncHttpClient.java:94)
	at com.hubspot.horizon.ning.NingAsyncHttpClient.internalExecute(NingAsyncHttpClient.java:102)
	at com.hubspot.horizon.ning.NingAsyncHttpClient.execute(NingAsyncHttpClient.java:66)
	at com.hubspot.horizon.ning.NingHttpClient.execute(NingHttpClient.java:37)
	at com.hubspot.horizon.ning.NingHttpClient.execute(NingHttpClient.java:28)
	at com.hubspot.singularity.client.SingularityClient.getCollectionWithParams(SingularityClient.java:246)

I've tried to use HorizonApache, but can't because NingHttpClient is hardcoded in SingularityClient.

It makes it impossible to use both Singularity and Elasticsearch in the same Java application.

**Comment by tpetr** [comment]
@jloisel sorry for the headache there -- we'll get this squared away, but a quick temporary workaround for you could be overriding [SingularityClientModule.configure()](https://github.com/HubSpot/Singularity/blob/master/SingularityClient/src/main/java/com/hubspot/singularity/client/SingularityClientModule.java#L46-L57) to bind a different HttpClient (i.e. HorizonApache).

@jhaber thoughts on how to best handle this? should Singularity have a shaded Horizon, or Horizon a shaded netty, or would that be a hellscape? or should we just bump the netty dep?

**Comment by jhaber** [comment]
The netty dependency comes transitively from async-http-client, I can bundle and relocate the netty dependency into HorizonNing though

**Comment by jloisel** [comment]
We managed to drop any dependency to your client by mapping all service calls we use by using [Retrofit](https://github.com/square/retrofit), with only a dependency to SingularityBase. So, the fix is not really urgent at the moment.

The best would be to:
- have a dependency on a module with only the http client interface,
- autoload the implementation being available in the classpath using a Java ServiceLoader,
- or have a way to configure the httpclient when building the SingularityClient.

This would allow to easily replace the Ning httpclient by the Apache one, or even a custom one.

Another solution would be to rewrite the client using Retrofit, which supports multiple httpclients. The whole client can fit into a single Interface.

```java
public interface SingularityApi {

  @POST("/requests/request/{requestId}/run")
  void run(
      @Path("requestId") String requestId, 
      @Query("user") String username, 
      @Body List<String> body,
      Callback<Response> callBack);

  @GET("/requests")
  List<SingularityRequestParent> getRequests();
  
  @GET("/requests/request/{id}")
  SingularityRequestParent getSingularityRequest(@Path("id") String id);
...
}
```

We cannot bump to 0.4.5 and above because we have to test it first. Last time we upgraded Singularity, we had incompatible changes which broke our server ("_" changed to "-" in region and slave names).

**Comment by jloisel** [comment]
We couldn't use Horizon Apache either, because due to another library we have a dependency to Apache 4.2.5 while yours uses HttpClient 4.4.x. We can't upgrade because it comes transitively from the other library :dash:

**Comment by jhaber** [comment]
To prevent conflicts, Horizon actually bundles and relocates the Apache HTTP classes, but due to a misconfiguration of the maven shade plugin it still had a transitive dependency on the Apache HTTP libraries (it is unused and safe to exclude though). This will be fixed in the next release

**Comment by jloisel** [comment]
Thanks for being reactive guys :)

Don't feel in a hurry, we're not depending on the SingularityClient anymore. We shouldn't experience any issue anymore until you change the Rest API ;)

**Comment by ssalinas** [comment]
@jhaber did we ever get this one fixed?

**Comment by jhaber** [comment]
The latest version of HorizonNing has this problem fixed, I just need to make sure Singularity is using a late enough version of Horizon

**Comment by ssalinas** [comment]
Cool, going to close this since current version fixes the issue, I'll keep going with the version bump as well just to keep us up to date
