### ISSUE TITLE
Actual "required" config vs overrides

### ISSUE THREAD

**Issue by scalp42** [HubSpot/Singularity#770]
Looking at the example config file provided:

https://github.com/HubSpot/Singularity/blob/master/Docs/install.md#5-create-singularity-config-file

Does "Singularity requires a YAML file with some configuration values in order to start up" mean:

1. you'll need all the **keys** specified in the example (value is yours to change).
2. you can omit some of the **keys** (assuming defaulting to some default values inside the app).

For example, I see the `server` block with for example the `type: simple` value but I have no idea what it implies, the `server` block doesn't appear in https://github.com/HubSpot/Singularity/blob/master/Docs/reference/configuration.md#singularity-configuration.

Thanks for the insight!

PS: the idea is to figure what need to be actually dumped to YAML on the provisioning side.

**Comment by tpetr** [comment]
Sorry for the delay here -- 2 is correct. The `server` block you're referring to is part of the base [Dropwizard configs](http://www.dropwizard.io/0.7.1/docs/manual/configuration.html), and I think we made a bad assumption that people would understand that. I'll update the docs to indicate which fields are required, and add an extra blurb about the DW-specific stuff.

**Comment by ssalinas** [comment]
Docs were updated and have a link to the base dropwizard configuration:
http://getsingularity.com/Docs/reference/configuration.html
