### ISSUE TITLE
Deploy that starts with a single instance, and only proceeds on manual approval

### ISSUE THREAD

**Issue by strykerd** [HubSpot/Singularity#799]
Thanks very much for your work on Singularity!

It would be great if Singularity supported a mode of deployment that I've used at previous companies.  The model is to deploy a single instance, and wait for human approval before continuing to deploy to the other instances of the service.  If the human approves of the single instance deployment, he manually tells the deployment system to continue the deployment by deploying the remaining instances.  If the human disapproves of the single instance deployment, the single instance is halted and the deployment is cancelled.

What I really like about this functionality is that it let's the engineer doing deployment take the time to verify that the instance is working correctly, and if he decides it is not correct, only a fraction of the customer based will have been exposed to the bad instance.

Obviously, it's fine if this new behavior is not default behavior, but instead triggered by a new command-line argument, or something of that sort.

Thanks,
David Stryker
OpenTable.com

**Comment by ssalinas** [comment]
Hi David. We are actually investigating something very similar internally and will be starting work on it soon. We'll be sure to tag you on the pull request when we get it out there

**Comment by ssalinas** [comment]
This was implemented in #817 and will be included in the next release
