### ISSUE TITLE
Docker parameters in UI

### ISSUE THREAD

**Issue by scalp42** [HubSpot/Singularity#897]
Would like to open this issue regarding the lack of UI on the tasks side.

It'd be great if Singularity could allow a "write" access by adding the the API resources in the new request UI bits:

![](https://i.imgur.com/QQBChE6.png)

Using Singularity 0.4.9, it's really limited (even more than in v0.4.5).

Maybe keep the current UI but allow an attribute to be specified in the YAML to allow adding tasks parameters like Marathon:

![](https://i.imgur.com/vRKfsSY.png)

Thoughts ?

**Comment by ssalinas** [comment]
@scalp42 most of what you are looking for is on the new deploy page. On the page for the request you just created, click on deploy and you will get a set of fields very similar to that. The request holds over-arching information for all deploys (number of instances, type of request, etc), while the individual deploy has information about the resources, docker image, ports, ...

**Comment by scalp42** [comment]
@ssalinas found it, but it's still more or less the same as in you can't pass a command for example to override the container one (you have to rely on the container one).

**Comment by ssalinas** [comment]
fixed by #962
