### ISSUE TITLE
API with JSON examples

### ISSUE THREAD

**Issue by scalp42** [HubSpot/Singularity#899]
It would be great if the API docs would show JSON examples for it. There's a lot of broken links within the markdown and it makes it pretty difficult.

Marathon inspiration would be great here to help, see: https://mesosphere.github.io/marathon/docs/rest-api.html

Thoughts?

**Comment by ssalinas** [comment]
We just gave the Singularity docs a bit of a makeover and I've added some more examples. Can check out the new docs at [getsingularity.com](getsingularity.com), or go right to the [examples page here](http://getsingularity.com/Docs/getting-started/basic-examples.html)

**Comment by scalp42** [comment]
wow @ssalinas we'll take a look! :+1:
