### ISSUE TITLE
Framework Authentication

### ISSUE THREAD

**Issue by cnocito** [HubSpot/Singularity#909]
Looking through the documentation, I didn't find any support for Framework authentication, which is consistent with this error:

I0219 13:00:31.122567  1734 sched.cpp:336] No credentials provided. Attempting to register without authentication
I0219 13:00:31.123420  1734 sched.cpp:1131] Got error 'Framework at scheduler-fd0ef15a-5149-4651-b61a-6f55f67cf06e@10.81.80.230:41701 is not authenticated'
I0219 13:00:31.123435  1734 sched.cpp:1941] Asked to abort the driver
I0219 13:00:31.123669  1734 sched.cpp:1177] Aborting framework 'Singularity'

Are there any plans to add this feature?

**Comment by ssalinas** [comment]
@cnocito we personally don't use it. However, we could implement it very easily by adding fields for the principal and secret in the mesos section of the Singularity configuration. Would that work for you?

**Comment by cnocito** [comment]
Yes, actually that would work great. Is Kerberos integration at all under the radar?

**Comment by tpetr** [comment]
@cnocito we don't have plans for Kerberos support in the near future, but I can walk you through the authentication extension points if you're interested in submitting a PR

**Comment by ssalinas** [comment]
@cnocito the PR for framework auth has been merged. You can add `credentialPrincipal` and `credentialSecret` in the `mesos` section of your SingularityService yaml config to enable the auth.

**Comment by cnocito** [comment]
Wow, that was fast, thanks! I'll test as soon as I get some free time. @tpetr we are still deciding on a framework, but if we go with Singularity you can walk me through the extension and I'll see if I can put something together.

**Comment by tpetr** [comment]
@cnocito I just realized I might have misunderstood you -- to clarify, are you hoping for Kerberos integration as part of Mesos framework authentication, or as part of the entire Singularity API?

**Comment by cnocito** [comment]
@tpetr sorry I wasn't very clear. As part of the Singularity API, so we have control over who get's to schedule jobs. I've been looking at fronting the API with a proxy that does this, but it would be much more better/elegant/easier to support if it's all integrated.
