### ISSUE TITLE
UI is broken with Singularity 0.4.10

### ISSUE THREAD

**Issue by scalp42** [HubSpot/Singularity#912]
If you managed to be able to click on things, they get duplicated:

![](https://i.imgur.com/DJeNJxE.png)

Also noticed you can't really click on that cross either:

![](https://i.imgur.com/3yywlhJ.png)

**Comment by ssalinas** [comment]
Looks like there is some css missing from the ui build

/cc @tpetr

**Comment by scalp42** [comment]
![Another one](http://cdn.pigeonsandplanes.com/wp-content/uploads/2015/12/fsdfdsfffff.gif):

![](https://i.imgur.com/3yywlhJ.png)

**Comment by ssalinas** [comment]
Yes, if portions of js/css are missing from the ui build it will be on most pages. We can try to get a fixed artifact out soon

**Comment by scalp42** [comment]
Sounds good, thanks for feedback :+1:

**Comment by tpetr** [comment]
Many apologies for the busted UI -- we've had a ton of issues with Brunch lately. Taking a look at this now.

**Comment by scalp42** [comment]
Oh please do not apologize, the project is much appreciated. I think we might just come back later to Singularity because of the quirks but kudos to you for open sourcing it :smile:

**Comment by ssalinas** [comment]
This is now fixed in the [0.4.11 release](https://github.com/HubSpot/Singularity/releases/tag/Singularity-0.4.11). I've made a note on the 0.4.10 release notes as well

**Comment by scalp42** [comment]
Confirmed!
