### ISSUE TITLE
Singularity captures Ctrl-T (new tab on Linux)

### ISSUE THREAD

**Issue by stevenschlansker** [HubSpot/Singularity#942]
You can use the 'T' key to search through requests from e.g. the Status screen.
This key binding also captures Ctrl-T.  This is fine on Mac, where "new tab" is Cmd-T.
But on Linux, it shadows the new tab Ctrl-T key binding.

Can the UI respond to a bare "T" press only, and ignore Ctrl-T?

**Comment by Calvinp** [comment]
That looks like a bug to me. I've opened a pull request to fix it.
https://github.com/HubSpot/Singularity/pull/943

**Comment by stevenschlansker** [comment]
Awesome, thanks!

**Comment by Calvinp** [comment]
This was just merged to Master, closing the issue.
