### ISSUE TITLE
swagger.json?

### ISSUE THREAD

**Issue by nyarly** [HubSpot/Singularity#956]
Is it possible to generate a Swagger spec from the annotations? I see that the swagger-maven-plugin in theory has the ability to do this, but I haven't been able to get it to actually do the generation.

The swagger.json would make it much easier to build API clients.

**Comment by ssalinas** [comment]
Updated our pom in #958 so that the json will be output during `mvn compile` alongside the other api-docs documents (in `target/classes/assets/api-docs`). If you need to use them sooner, feel free to mvn compile from the `swagger_json` branch to generate them
