### ISSUE TITLE
Swagger docs - invalid $ref fields

### ISSUE THREAD

**Issue by nyarly** [HubSpot/Singularity#967]
There are several fields in both the swagger JSON api documents and the markdown documentation that aren't valid - $ref fields on properties (as I understand it, and per https://github.com/OAI/OpenAPI-Specification/blob/master/versions/1.2.md#433-data-type-fields) have to refer to a model id, and several in the docs are raw Java types. 

For example, https://github.com/HubSpot/Singularity/blob/master/Docs/reference/apidocs/models.md#-commandinfo includes
urisOrBuilderList: List[? extends org.apache.mesos.Protos$CommandInfo$URIOrBuilder]

Maybe that should be "array" with an items field as well? Or else the field should be excluded from the Swagger docs?

**Comment by ssalinas** [comment]
Fixed in #1350 , One of the models was pulling in all the mesos Protos fields and that was messing things up. Since it is just a model we return and not one needed for POSTing to Singularity, I had swagger ignore those fields to make the docs cleaner
