### ISSUE TITLE
Add Missing Request Properties to Create/Edit UI

### ISSUE THREAD

**Issue by bradjorgensen** [HubSpot/Singularity#973]
The UI for creating and editing requests is missing properties like `requiredSlaveAttributes`.  If any of the missing properties are set on a request, you can't edit it from the UI since it will remove them.  This might already be a part of or another thing to add to pull request #962.

**Comment by Calvinp** [comment]
Sorry for how long this took. This is implemented in #1195 and released in 0.10.0.
